-- Tracker V2 — V2 Step 3.
--
-- Three new tables + a status column on learning_updates so the
-- "Submit" tab can stage pending entries before they go live.
--
-- tracker_use_cases     newsroom-submitted accounts of "what happened
--                       when we used Grounded for X." Optionally shared
--                       cohort-wide. Powers the Use Cases tab.
--
-- tracker_relationships explicit links between learning_updates rows
--                       (cited_in / superseded_by / applies_to /
--                       derived_from). Powers the Connections map tab.
--
-- tracker_digests       weekly cohort digests of the most-important
--                       new entries. Auto-generated by a pg-boss job;
--                       surfaced at the top of the Home tab.
--
-- learning_updates.status — new column. 'live' is the default (existing
--                       rows + default seed). 'pending' covers
--                       newsroom-submitted entries awaiting admin
--                       approval. 'archived' covers admin-retired
--                       entries we want to keep for history but hide
--                       from the feed. listUpdates() and the Tracker
--                       agent search are updated to filter status='live'.

ALTER TABLE learning_updates
  ADD COLUMN status TEXT NOT NULL DEFAULT 'live'
    CHECK (status IN ('live', 'pending', 'archived'));

CREATE INDEX learning_updates_status_idx ON learning_updates (status);

CREATE TABLE tracker_use_cases (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  newsroom_id UUID NOT NULL REFERENCES newsrooms(id) ON DELETE CASCADE,
  submitted_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  -- 'positive': it worked and we'd recommend the pattern.
  -- 'negative': it didn't work and we want others to know what went wrong.
  -- 'mixed': it partially worked; nuances are in the summary.
  outcome TEXT NOT NULL DEFAULT 'positive'
    CHECK (outcome IN ('positive', 'negative', 'mixed')),
  -- Which agents were involved. Used for filtering + cross-reference.
  agents_involved TEXT[] NOT NULL DEFAULT '{}',
  -- Free-form tags (POPIA, source-protection, etc.). Newsrooms tag freely.
  tags TEXT[] NOT NULL DEFAULT '{}',
  attachment_urls TEXT[] NOT NULL DEFAULT '{}',
  -- Default false. The newsroom can flip to true to share with the cohort.
  shared_with_cohort BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX tracker_use_cases_newsroom_id_idx ON tracker_use_cases (newsroom_id);
CREATE INDEX tracker_use_cases_shared_idx ON tracker_use_cases (shared_with_cohort) WHERE shared_with_cohort = TRUE;
CREATE INDEX tracker_use_cases_created_at_idx ON tracker_use_cases (created_at DESC);
CREATE INDEX tracker_use_cases_outcome_idx ON tracker_use_cases (outcome);

CREATE TABLE tracker_relationships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  from_entry_id UUID NOT NULL REFERENCES learning_updates(id) ON DELETE CASCADE,
  to_entry_id UUID NOT NULL REFERENCES learning_updates(id) ON DELETE CASCADE,
  kind TEXT NOT NULL
    CHECK (kind IN ('cited_in', 'superseded_by', 'applies_to', 'derived_from', 'related_to')),
  notes TEXT,
  -- newsroom_id NULL = cohort-wide relationship (admin-curated). Non-NULL =
  -- newsroom-private link (a newsroom mapping connections for itself).
  newsroom_id UUID REFERENCES newsrooms(id) ON DELETE CASCADE,
  created_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Guardrail: no self-loops.
  CONSTRAINT tracker_rel_no_self CHECK (from_entry_id <> to_entry_id),
  -- One link per (from, to, kind) pair per scope.
  UNIQUE (from_entry_id, to_entry_id, kind, newsroom_id)
);

CREATE INDEX tracker_relationships_from_idx ON tracker_relationships (from_entry_id);
CREATE INDEX tracker_relationships_to_idx ON tracker_relationships (to_entry_id);
CREATE INDEX tracker_relationships_newsroom_idx ON tracker_relationships (newsroom_id);

CREATE TABLE tracker_digests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- newsroom_id NULL = cohort-wide digest (the V2 default; one digest per
  -- period). Non-NULL = per-newsroom personalised digest (future).
  newsroom_id UUID REFERENCES newsrooms(id) ON DELETE CASCADE,
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  summary_md TEXT NOT NULL,
  top_entry_ids UUID[] NOT NULL DEFAULT '{}',
  entry_count INTEGER NOT NULL DEFAULT 0,
  -- Audit: which model generated the summary (Haiku-only by policy).
  generated_by_model TEXT,
  cost_usd NUMERIC(10, 6),
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX tracker_digests_newsroom_idx ON tracker_digests (newsroom_id);
CREATE INDEX tracker_digests_period_idx ON tracker_digests (period_end DESC);
