-- 039_tracker_import.sql
-- GENERATED by scripts/tracker/build-import.js from the Tracker app pg_dump.
-- Do not edit by hand — re-run the generator. Source of truth: the dump.
--
-- AI-Legal core tables imported as-is; all other tables prefixed tracker_;
-- the legacy migrations table is excluded; OWNER/GRANT/COMMENT/data stripped.
-- FTS + fan-out functions/triggers are appended at the end (they reference only as-is tables).
-- Data loads separately (one-shot): node scripts/tracker/build-import.js --data
-- Tables: 59 (15 as-is, 44 prefixed). Excluded: migrations.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.tracker_agent_conversations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    agent_type character varying(50) NOT NULL,
    user_id uuid,
    title character varying(255),
    messages jsonb DEFAULT '[]'::jsonb NOT NULL,
    context jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_ai_conversations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    course_id uuid,
    user_id uuid,
    title character varying(255),
    messages jsonb DEFAULT '[]'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_ai_interactions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    interaction_type character varying(100) NOT NULL,
    sector_id uuid,
    entity_type character varying(50),
    entity_id uuid,
    knowledge_ids_used uuid[],
    input_summary character varying(1000),
    output_text text,
    output_tokens integer,
    was_used boolean,
    user_rating integer,
    user_edits text,
    feedback_notes text,
    user_id uuid,
    duration_ms integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ai_interactions_user_rating_check CHECK (((user_rating >= 1) AND (user_rating <= 5)))
);

CREATE TABLE public.ai_lawsuit_events (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    lawsuit_id uuid NOT NULL,
    event_date date,
    event_type character varying(50) DEFAULT 'update'::character varying NOT NULL,
    title character varying(500),
    description text,
    source_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_verified_at timestamp with time zone
);

CREATE TABLE public.ai_lawsuits (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    case_name character varying(500) NOT NULL,
    plaintiffs text[] DEFAULT '{}'::text[],
    defendants text[] DEFAULT '{}'::text[],
    court character varying(300),
    judge character varying(200),
    jurisdiction character varying(100),
    district character varying(200),
    circuit character varying(100),
    status character varying(50) DEFAULT 'active'::character varying,
    case_type character varying(100) DEFAULT 'copyright'::character varying,
    key_issues text[] DEFAULT '{}'::text[],
    filing_date date,
    last_update date,
    next_deadline date,
    next_deadline_notes text,
    outcome text,
    settlement_amount character varying(200),
    case_url text,
    source_url text,
    summary text,
    curriculum_relevance text,
    is_curriculum_relevant boolean DEFAULT true,
    tags text[] DEFAULT '{}'::text[],
    external_id character varying(200),
    last_scraped_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    detailed_analysis text,
    knowledge_entry_id uuid,
    analysis_generated_at timestamp with time zone,
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    search_tsv tsvector,
    importance_score numeric(5,2),
    importance_reasoning text,
    importance_signals jsonb,
    importance_scored_at timestamp with time zone
);

CREATE TABLE public.ai_legal_api_keys (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    key_hash text NOT NULL,
    key_prefix character varying(16) NOT NULL,
    owner_name character varying(200) NOT NULL,
    owner_email character varying(320),
    description text,
    tier character varying(40) DEFAULT 'free'::character varying NOT NULL,
    daily_limit integer DEFAULT 10000 NOT NULL,
    requests_today integer DEFAULT 0 NOT NULL,
    window_start date DEFAULT CURRENT_DATE NOT NULL,
    last_used_at timestamp with time zone,
    last_used_ip inet,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_insights (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    subject_kind character varying(20) NOT NULL,
    subject_id uuid NOT NULL,
    insight_type character varying(30) NOT NULL,
    content text NOT NULL,
    citations jsonb DEFAULT '[]'::jsonb NOT NULL,
    model_used character varying(100),
    confidence numeric(3,2),
    generated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_notifications (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    subscription_id uuid NOT NULL,
    event_kind character varying(20) NOT NULL,
    event_id uuid NOT NULL,
    status character varying(20) DEFAULT 'queued'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sent_at timestamp with time zone,
    attempt_count integer DEFAULT 0 NOT NULL,
    error_message text,
    CONSTRAINT ai_legal_notifications_event_kind_check CHECK (((event_kind)::text = ANY ((ARRAY['lawsuit_event'::character varying, 'regulation_event'::character varying])::text[]))),
    CONSTRAINT ai_legal_notifications_status_check CHECK (((status)::text = ANY ((ARRAY['queued'::character varying, 'sent'::character varying, 'failed'::character varying, 'skipped'::character varying])::text[])))
);

CREATE TABLE public.ai_legal_raw_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    source_id uuid NOT NULL,
    external_id text,
    url text,
    title text,
    content text,
    author text,
    published_at timestamp with time zone,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload jsonb,
    triage_status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    triage_result jsonb,
    triaged_at timestamp with time zone,
    lawsuit_id uuid,
    regulation_id uuid,
    event_id uuid
);

CREATE TABLE public.ai_legal_source_mentions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    subject_kind character varying(20) NOT NULL,
    subject_id uuid NOT NULL,
    url text NOT NULL,
    canonical_url text,
    host character varying(300),
    title character varying(800),
    author character varying(300),
    site_name character varying(200),
    description text,
    body_excerpt text,
    image_url text,
    published_at timestamp with time zone,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    http_status integer,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_source_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    source_id uuid NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    items_seen integer DEFAULT 0 NOT NULL,
    items_new integer DEFAULT 0 NOT NULL,
    items_duplicate integer DEFAULT 0 NOT NULL,
    status character varying(30) DEFAULT 'running'::character varying NOT NULL,
    error text
);

CREATE TABLE public.ai_legal_sources (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(300) NOT NULL,
    kind character varying(30) NOT NULL,
    url text NOT NULL,
    jurisdiction character varying(200),
    tags text[] DEFAULT '{}'::text[],
    active boolean DEFAULT true NOT NULL,
    run_frequency_hours integer DEFAULT 6 NOT NULL,
    last_run_at timestamp with time zone,
    last_success_at timestamp with time zone,
    last_error text,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    items_seen integer DEFAULT 0 NOT NULL,
    items_new integer DEFAULT 0 NOT NULL,
    items_promoted integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_subscriptions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    entity_kind character varying(20) NOT NULL,
    entity_id uuid,
    email character varying(320) NOT NULL,
    confirmed_at timestamp with time zone,
    confirm_token character varying(64) NOT NULL,
    unsubscribe_token character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    unsubscribed_at timestamp with time zone,
    last_sent_at timestamp with time zone,
    CONSTRAINT ai_legal_subscriptions_check CHECK (((((entity_kind)::text = 'all'::text) AND (entity_id IS NULL)) OR (((entity_kind)::text <> 'all'::text) AND (entity_id IS NOT NULL)))),
    CONSTRAINT ai_legal_subscriptions_entity_kind_check CHECK (((entity_kind)::text = ANY ((ARRAY['lawsuit'::character varying, 'regulation'::character varying, 'all'::character varying])::text[])))
);

CREATE TABLE public.ai_legal_tools (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(300) NOT NULL,
    kind character varying(20) DEFAULT 'tool'::character varying NOT NULL,
    vendor character varying(300),
    category character varying(50),
    description text,
    url text,
    pricing character varying(30),
    strengths text,
    limitations text,
    integrations text[] DEFAULT '{}'::text[],
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    logo_url text,
    tags text[] DEFAULT '{}'::text[],
    is_published boolean DEFAULT true NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_usecases (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    firm_name character varying(300) NOT NULL,
    firm_type character varying(30),
    jurisdiction character varying(200),
    use_case_title character varying(500) NOT NULL,
    summary text,
    tools_used text[] DEFAULT '{}'::text[],
    categories text[] DEFAULT '{}'::text[],
    outcome text,
    quantified_impact character varying(500),
    source_url text NOT NULL,
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    source_name character varying(300),
    author character varying(300),
    published_at timestamp with time zone,
    verified_at timestamp with time zone,
    tags text[] DEFAULT '{}'::text[],
    is_published boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_user_submissions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    submission_kind character varying(20) DEFAULT 'lawsuit'::character varying NOT NULL,
    case_name character varying(500),
    jurisdiction character varying(200),
    parties text,
    source_url text NOT NULL,
    summary text,
    submitter_email character varying(300),
    submitter_ip character varying(45),
    submitter_ua text,
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    review_notes text,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    promoted_to_lawsuit_id uuid,
    promoted_to_regulation_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_regulation_events (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    regulation_id uuid NOT NULL,
    event_date date,
    event_type character varying(50) DEFAULT 'update'::character varying NOT NULL,
    title character varying(500),
    description text,
    source_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_verified_at timestamp with time zone
);

CREATE TABLE public.ai_regulations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    regulation_name character varying(500) NOT NULL,
    short_name character varying(200),
    jurisdiction character varying(200) NOT NULL,
    regulator character varying(300),
    status character varying(50) DEFAULT 'in_force'::character varying,
    regulation_type character varying(100),
    scope text[] DEFAULT '{}'::text[],
    affected_sectors text[] DEFAULT '{}'::text[],
    proposed_date date,
    enacted_date date,
    effective_date date,
    enforcement_date date,
    next_milestone date,
    next_milestone_notes text,
    key_provisions text[] DEFAULT '{}'::text[],
    penalties text,
    extraterritorial_scope text,
    official_url text,
    source_url text,
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    summary text,
    detailed_analysis text,
    analysis_generated_at timestamp with time zone,
    curriculum_relevance text,
    is_curriculum_relevant boolean DEFAULT true,
    tags text[] DEFAULT '{}'::text[],
    knowledge_entry_id uuid,
    external_id character varying(200),
    last_scraped_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    search_tsv tsvector,
    importance_score numeric(5,2),
    importance_reasoning text,
    importance_signals jsonb,
    importance_scored_at timestamp with time zone
);

CREATE TABLE public.tracker_assessment_questions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    question_text text NOT NULL,
    question_type character varying(50) DEFAULT 'text'::character varying NOT NULL,
    options jsonb,
    order_index integer DEFAULT 0 NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_background_jobs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    cron_expression character varying(50) NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    last_run_at timestamp with time zone,
    next_run_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_cohort_courses (
    cohort_id uuid NOT NULL,
    course_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_cohort_organisations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    cohort_id uuid NOT NULL,
    organisation_id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_cohort_participants (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    cohort_id uuid NOT NULL,
    contact_id uuid NOT NULL,
    status character varying(50) DEFAULT 'enrolled'::character varying NOT NULL,
    completion_date date,
    cpd_certificate_issued boolean DEFAULT false NOT NULL,
    feedback_score integer,
    feedback_notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT cohort_participants_feedback_score_check CHECK (((feedback_score >= 1) AND (feedback_score <= 10)))
);

CREATE TABLE public.tracker_cohort_sessions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    cohort_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    session_date date,
    start_time time without time zone,
    end_time time without time zone,
    location character varying(255),
    notes text,
    order_index integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_cohorts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    client_organisation_id uuid,
    name character varying(255) NOT NULL,
    delivery_type character varying(50) DEFAULT 'online_3x2hr'::character varying NOT NULL,
    status character varying(50) DEFAULT 'planned'::character varying NOT NULL,
    start_date date,
    end_date date,
    trainer_id uuid,
    max_participants integer,
    cpd_hours numeric,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_contacts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    email character varying(255),
    phone character varying(50),
    job_title character varying(200),
    organisation_id uuid,
    linkedin_url character varying(500),
    notes text,
    tags text[] DEFAULT '{}'::text[],
    pipeline_stage character varying(50) DEFAULT 'prospect'::character varying NOT NULL,
    source character varying(100),
    last_contacted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_course_modules (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    course_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    order_index integer DEFAULT 0 NOT NULL,
    duration_minutes integer,
    content text,
    content_url character varying(500),
    video_url character varying(500),
    feedback_notes text,
    effectiveness_rating integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT course_modules_effectiveness_rating_check CHECK (((effectiveness_rating >= 1) AND (effectiveness_rating <= 5)))
);

CREATE TABLE public.tracker_courses (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    delivery_type character varying(50) DEFAULT 'both'::character varying NOT NULL,
    version character varying(20) DEFAULT 'v1.0'::character varying,
    status character varying(50) DEFAULT 'draft'::character varying NOT NULL,
    last_updated_by uuid,
    effectiveness_score numeric,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    notes text
);

CREATE TABLE public.tracker_document_templates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    type character varying(50) NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    template_prompt text NOT NULL,
    structure jsonb,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_engagement_milestones (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    engagement_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description text,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    due_date date,
    completed_at timestamp with time zone,
    draft_url character varying(500),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_engagement_sessions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    engagement_id uuid NOT NULL,
    session_date date,
    duration_minutes integer,
    notes text,
    next_steps text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_feedback (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    page character varying(255),
    category character varying(50) DEFAULT 'feature'::character varying NOT NULL,
    content text NOT NULL,
    claude_prompt text,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    priority character varying(20) DEFAULT 'medium'::character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_funders (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) DEFAULT 'foundation'::character varying NOT NULL,
    website character varying(500),
    contact_name character varying(255),
    contact_email character varying(255),
    country character varying(100),
    notes text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_funding_applications (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    opportunity_id uuid NOT NULL,
    title character varying(255),
    status character varying(50) DEFAULT 'drafting'::character varying NOT NULL,
    submitted_at timestamp with time zone,
    decision_at timestamp with time zone,
    amount_requested numeric,
    amount_awarded numeric,
    content text,
    budget_breakdown jsonb DEFAULT '[]'::jsonb,
    assigned_to uuid,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_funding_opportunities (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    funder_id uuid,
    sector_id uuid,
    title character varying(255) NOT NULL,
    description text,
    amount_min numeric,
    amount_max numeric,
    currency character varying(10) DEFAULT 'GBP'::character varying NOT NULL,
    deadline timestamp with time zone,
    status character varying(50) DEFAULT 'researching'::character varying NOT NULL,
    pipeline_stage character varying(50) DEFAULT 'identified'::character varying NOT NULL,
    priority character varying(20) DEFAULT 'medium'::character varying NOT NULL,
    match_funding_required boolean DEFAULT false NOT NULL,
    match_funding_amount numeric,
    eligibility_notes text,
    ai_research_notes text,
    url character varying(500),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_funding_reports (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    application_id uuid NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(50) DEFAULT 'interim'::character varying NOT NULL,
    status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    due_date date,
    submitted_at timestamp with time zone,
    content text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_generated_documents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    template_id uuid,
    sector_id uuid NOT NULL,
    organisation_id uuid,
    assessment_id uuid,
    title character varying(255) NOT NULL,
    content text,
    status character varying(50) DEFAULT 'draft'::character varying NOT NULL,
    generated_by uuid,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    was_published boolean DEFAULT false,
    published_at timestamp with time zone
);

CREATE TABLE public.tracker_gmail_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_email character varying(255) NOT NULL,
    access_token text,
    refresh_token text NOT NULL,
    token_expiry timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_industry_intelligence (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid,
    category character varying(100) NOT NULL,
    title character varying(500) NOT NULL,
    summary text NOT NULL,
    details text,
    source character varying(500),
    source_url character varying(1000),
    relevance_score numeric(3,2),
    is_actionable boolean DEFAULT false,
    action_taken text,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    discovered_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    embedding public.vector(384)
);

CREATE TABLE public.tracker_job_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    job_id uuid NOT NULL,
    status character varying(50) DEFAULT 'running'::character varying NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    completed_at timestamp with time zone,
    result text,
    items_processed integer DEFAULT 0,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_knowledge_entries (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    category character varying(100) NOT NULL,
    subcategory character varying(100),
    title character varying(500) NOT NULL,
    content text NOT NULL,
    sector_id uuid,
    organisation_id uuid,
    course_id uuid,
    source_type character varying(100) NOT NULL,
    source_id uuid,
    source_description character varying(500),
    confidence numeric(3,2) DEFAULT 0.5,
    is_verified boolean DEFAULT false,
    usage_count integer DEFAULT 0,
    last_used_at timestamp with time zone,
    expires_at timestamp with time zone,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    source_url character varying(1000),
    embedding public.vector(384)
);

CREATE TABLE public.tracker_knowledge_tags (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    knowledge_id uuid NOT NULL,
    tag character varying(100) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_learning_journeys (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    contact_id uuid NOT NULL,
    organisation_id uuid,
    sector_id uuid,
    status character varying(50) DEFAULT 'active'::character varying NOT NULL,
    started_at date DEFAULT CURRENT_DATE,
    overall_progress integer DEFAULT 0,
    skill_level character varying(20) DEFAULT 'beginner'::character varying,
    ai_notes text,
    last_activity_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_learning_outcomes (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    course_id uuid,
    module_id uuid,
    title character varying(255) NOT NULL,
    description text,
    assessment_criteria text,
    order_index integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_learning_tasks (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    participant_id uuid,
    contact_id uuid NOT NULL,
    cohort_id uuid,
    outcome_id uuid,
    title character varying(255) NOT NULL,
    description text,
    task_type character varying(50) DEFAULT 'deliverable'::character varying NOT NULL,
    difficulty character varying(20) DEFAULT 'beginner'::character varying,
    due_date date,
    status character varying(50) DEFAULT 'assigned'::character varying NOT NULL,
    submitted_at timestamp with time zone,
    submission_text text,
    submission_url character varying(500),
    reviewer_id uuid,
    review_notes text,
    review_score integer,
    ai_review text,
    approved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT learning_tasks_review_score_check CHECK (((review_score >= 1) AND (review_score <= 5)))
);

CREATE TABLE public.tracker_needs_assessments (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    organisation_id uuid,
    contact_id uuid,
    status character varying(50) DEFAULT 'draft'::character varying NOT NULL,
    responses jsonb DEFAULT '[]'::jsonb,
    ai_analysis text,
    recommended_tier character varying(50),
    submitted_at timestamp with time zone,
    analysed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    knowledge_extracted boolean DEFAULT false
);

CREATE TABLE public.tracker_newsletter_digests (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    digest_date date NOT NULL,
    content text NOT NULL,
    item_count integer DEFAULT 0 NOT NULL,
    curriculum_count integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    version integer DEFAULT 1 NOT NULL,
    is_current boolean DEFAULT true NOT NULL
);

CREATE TABLE public.tracker_newsletter_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    gmail_message_id character varying(255),
    sender character varying(500),
    subject character varying(500),
    received_at timestamp with time zone,
    raw_text text,
    summary text,
    category character varying(100),
    is_curriculum_relevant boolean DEFAULT false,
    curriculum_relevance_reason text,
    relevant_sectors text[],
    is_digested boolean DEFAULT false,
    digest_date date,
    promoted_to_knowledge boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_url character varying(1000),
    source_type character varying(20) DEFAULT 'email'::character varying NOT NULL,
    is_rejected boolean DEFAULT false NOT NULL,
    rejected_at timestamp with time zone
);

CREATE TABLE public.tracker_notifications (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    user_id uuid,
    type character varying(50) DEFAULT 'alert'::character varying NOT NULL,
    title character varying(255) NOT NULL,
    message text,
    link character varying(500),
    is_read boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_organisations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(100),
    country character varying(100),
    city character varying(100),
    website character varying(500),
    notes text,
    relationship_stage character varying(50) DEFAULT 'prospect'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    relationship_type character varying(50) DEFAULT 'lead'::character varying,
    funder_organisation_id uuid,
    programme_name character varying(255),
    latitude numeric,
    longitude numeric
);

CREATE TABLE public.tracker_outreach_campaigns (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(50) DEFAULT 'cold_email'::character varying NOT NULL,
    status character varying(50) DEFAULT 'draft'::character varying NOT NULL,
    target_audience text,
    start_date date,
    end_date date,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_outreach_messages (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    campaign_id uuid,
    contact_id uuid,
    channel character varying(50) DEFAULT 'email'::character varying NOT NULL,
    subject character varying(500),
    body text,
    status character varying(50) DEFAULT 'draft'::character varying NOT NULL,
    sent_at timestamp with time zone,
    replied_at timestamp with time zone,
    gmail_message_id character varying(255),
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_participant_tokens (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    contact_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    email character varying(255),
    is_active boolean DEFAULT true NOT NULL,
    last_accessed_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_prompt_templates (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    function_name character varying(100) NOT NULL,
    base_prompt text NOT NULL,
    knowledge_query jsonb,
    is_active boolean DEFAULT true,
    version integer DEFAULT 1,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_sectors (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(100) NOT NULL,
    description text,
    colour character varying(7) DEFAULT '#6B7280'::character varying NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_service_engagements (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    organisation_id uuid,
    contact_id uuid,
    type character varying(50) NOT NULL,
    status character varying(50) DEFAULT 'scoping'::character varying NOT NULL,
    mentor_id uuid,
    start_date date,
    end_date date,
    session_count integer DEFAULT 0,
    deliverable_url character varying(500),
    document_id uuid,
    assessment_id uuid,
    notes text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_social_posts (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid NOT NULL,
    platform character varying(50) DEFAULT 'linkedin'::character varying NOT NULL,
    content text,
    status character varying(50) DEFAULT 'draft'::character varying NOT NULL,
    scheduled_for timestamp with time zone,
    published_at timestamp with time zone,
    ai_generated boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_team_members (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(200) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255),
    role character varying(50) DEFAULT 'trainer'::character varying NOT NULL,
    sector_ids uuid[] DEFAULT '{}'::uuid[],
    bio text,
    is_active boolean DEFAULT true NOT NULL,
    admin_access boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.tracker_uploaded_documents (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    filename character varying(500) NOT NULL,
    original_name character varying(500) NOT NULL,
    mime_type character varying(100) NOT NULL,
    file_size integer NOT NULL,
    file_path character varying(1000) NOT NULL,
    entity_type character varying(50),
    entity_id uuid,
    sector_id uuid,
    extracted_text text,
    extraction_status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    extraction_error text,
    ai_summary text,
    ai_extracted_data jsonb,
    ai_analysis_status character varying(50) DEFAULT 'pending'::character varying NOT NULL,
    uploaded_by uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE ONLY public.tracker_agent_conversations
    ADD CONSTRAINT tracker_agent_conversations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_ai_conversations
    ADD CONSTRAINT tracker_ai_conversations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_ai_interactions
    ADD CONSTRAINT tracker_ai_interactions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_lawsuit_events
    ADD CONSTRAINT ai_lawsuit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_lawsuits
    ADD CONSTRAINT ai_lawsuits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_api_keys
    ADD CONSTRAINT ai_legal_api_keys_key_hash_key UNIQUE (key_hash);

ALTER TABLE ONLY public.ai_legal_api_keys
    ADD CONSTRAINT ai_legal_api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_insights
    ADD CONSTRAINT ai_legal_insights_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_insights
    ADD CONSTRAINT ai_legal_insights_unique UNIQUE (subject_kind, subject_id, insight_type);

ALTER TABLE ONLY public.ai_legal_notifications
    ADD CONSTRAINT ai_legal_notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_dedup UNIQUE (source_id, external_id);

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_source_mentions
    ADD CONSTRAINT ai_legal_source_mentions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_source_mentions
    ADD CONSTRAINT ai_legal_source_mentions_unique UNIQUE (subject_kind, subject_id, url);

ALTER TABLE ONLY public.ai_legal_source_runs
    ADD CONSTRAINT ai_legal_source_runs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_sources
    ADD CONSTRAINT ai_legal_sources_kind_url_uniq UNIQUE (kind, url);

ALTER TABLE ONLY public.ai_legal_sources
    ADD CONSTRAINT ai_legal_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_subscriptions
    ADD CONSTRAINT ai_legal_subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_tools
    ADD CONSTRAINT ai_legal_tools_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_tools
    ADD CONSTRAINT ai_legal_tools_unique UNIQUE (kind, name);

ALTER TABLE ONLY public.ai_legal_usecases
    ADD CONSTRAINT ai_legal_usecases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_user_submissions
    ADD CONSTRAINT ai_legal_user_submissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_regulation_events
    ADD CONSTRAINT ai_regulation_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_regulations
    ADD CONSTRAINT ai_regulations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_assessment_questions
    ADD CONSTRAINT tracker_assessment_questions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_background_jobs
    ADD CONSTRAINT tracker_background_jobs_name_key UNIQUE (name);

ALTER TABLE ONLY public.tracker_background_jobs
    ADD CONSTRAINT tracker_background_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_cohort_courses
    ADD CONSTRAINT tracker_cohort_courses_cohort_id_course_id_key UNIQUE (cohort_id, course_id);

ALTER TABLE ONLY public.tracker_cohort_organisations
    ADD CONSTRAINT tracker_cohort_organisations_cohort_id_organisation_id_key UNIQUE (cohort_id, organisation_id);

ALTER TABLE ONLY public.tracker_cohort_organisations
    ADD CONSTRAINT tracker_cohort_organisations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_cohort_participants
    ADD CONSTRAINT tracker_cohort_participants_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_cohort_sessions
    ADD CONSTRAINT tracker_cohort_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_cohorts
    ADD CONSTRAINT tracker_cohorts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_contacts
    ADD CONSTRAINT tracker_contacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_course_modules
    ADD CONSTRAINT tracker_course_modules_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_courses
    ADD CONSTRAINT tracker_courses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_document_templates
    ADD CONSTRAINT tracker_document_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_engagement_milestones
    ADD CONSTRAINT tracker_engagement_milestones_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_engagement_sessions
    ADD CONSTRAINT tracker_engagement_sessions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_feedback
    ADD CONSTRAINT tracker_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_funders
    ADD CONSTRAINT tracker_funders_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_funding_applications
    ADD CONSTRAINT tracker_funding_applications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_funding_opportunities
    ADD CONSTRAINT tracker_funding_opportunities_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_funding_reports
    ADD CONSTRAINT tracker_funding_reports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_generated_documents
    ADD CONSTRAINT tracker_generated_documents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_gmail_tokens
    ADD CONSTRAINT tracker_gmail_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_industry_intelligence
    ADD CONSTRAINT tracker_industry_intelligence_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_job_runs
    ADD CONSTRAINT tracker_job_runs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_knowledge_entries
    ADD CONSTRAINT tracker_knowledge_entries_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_knowledge_tags
    ADD CONSTRAINT tracker_knowledge_tags_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_learning_journeys
    ADD CONSTRAINT tracker_learning_journeys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_learning_outcomes
    ADD CONSTRAINT tracker_learning_outcomes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_learning_tasks
    ADD CONSTRAINT tracker_learning_tasks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_needs_assessments
    ADD CONSTRAINT tracker_needs_assessments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_newsletter_digests
    ADD CONSTRAINT tracker_newsletter_digests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_newsletter_items
    ADD CONSTRAINT tracker_newsletter_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_notifications
    ADD CONSTRAINT tracker_notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_organisations
    ADD CONSTRAINT tracker_organisations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_outreach_campaigns
    ADD CONSTRAINT tracker_outreach_campaigns_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_outreach_messages
    ADD CONSTRAINT tracker_outreach_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_participant_tokens
    ADD CONSTRAINT tracker_participant_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_prompt_templates
    ADD CONSTRAINT tracker_prompt_templates_function_name_key UNIQUE (function_name);

ALTER TABLE ONLY public.tracker_prompt_templates
    ADD CONSTRAINT tracker_prompt_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_sectors
    ADD CONSTRAINT tracker_sectors_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_sectors
    ADD CONSTRAINT tracker_sectors_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_social_posts
    ADD CONSTRAINT tracker_social_posts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_team_members
    ADD CONSTRAINT tracker_team_members_email_key UNIQUE (email);

ALTER TABLE ONLY public.tracker_team_members
    ADD CONSTRAINT tracker_team_members_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_uploaded_documents
    ADD CONSTRAINT tracker_uploaded_documents_pkey PRIMARY KEY (id);

CREATE INDEX tracker_idx_agent_conversations_type ON public.tracker_agent_conversations USING btree (agent_type);

CREATE INDEX tracker_idx_agent_conversations_user ON public.tracker_agent_conversations USING btree (user_id);

CREATE INDEX tracker_idx_ai_conversations_course ON public.tracker_ai_conversations USING btree (course_id);

CREATE INDEX tracker_idx_ai_interactions_created ON public.tracker_ai_interactions USING btree (created_at DESC);

CREATE INDEX tracker_idx_ai_interactions_entity ON public.tracker_ai_interactions USING btree (entity_type, entity_id);

CREATE INDEX tracker_idx_ai_interactions_type ON public.tracker_ai_interactions USING btree (interaction_type);

CREATE UNIQUE INDEX idx_ai_lawsuits_case_name ON public.ai_lawsuits USING btree (case_name);

CREATE INDEX idx_ai_lawsuits_case_type ON public.ai_lawsuits USING btree (case_type);

CREATE INDEX idx_ai_lawsuits_defendants ON public.ai_lawsuits USING gin (defendants);

CREATE INDEX idx_ai_lawsuits_filing_date ON public.ai_lawsuits USING btree (filing_date DESC NULLS LAST);

CREATE INDEX idx_ai_lawsuits_importance ON public.ai_lawsuits USING btree (importance_score DESC NULLS LAST);

CREATE INDEX idx_ai_lawsuits_jurisdiction ON public.ai_lawsuits USING btree (jurisdiction);

CREATE INDEX idx_ai_lawsuits_key_issues ON public.ai_lawsuits USING gin (key_issues);

CREATE INDEX idx_ai_lawsuits_last_update ON public.ai_lawsuits USING btree (last_update DESC NULLS LAST);

CREATE INDEX idx_ai_lawsuits_plaintiffs ON public.ai_lawsuits USING gin (plaintiffs);

CREATE INDEX idx_ai_lawsuits_search_tsv ON public.ai_lawsuits USING gin (search_tsv);

CREATE INDEX idx_ai_lawsuits_status ON public.ai_lawsuits USING btree (status);

CREATE INDEX idx_ai_lawsuits_tags ON public.ai_lawsuits USING gin (tags);

CREATE INDEX idx_ai_lawsuits_updated ON public.ai_lawsuits USING btree (updated_at DESC);

CREATE INDEX idx_ai_legal_insights_subject ON public.ai_legal_insights USING btree (subject_kind, subject_id);

CREATE INDEX idx_ai_legal_insights_type ON public.ai_legal_insights USING btree (insight_type);

CREATE INDEX idx_ai_legal_raw_items_fetched ON public.ai_legal_raw_items USING btree (fetched_at DESC);

CREATE INDEX idx_ai_legal_raw_items_lawsuit ON public.ai_legal_raw_items USING btree (lawsuit_id) WHERE (lawsuit_id IS NOT NULL);

CREATE INDEX idx_ai_legal_raw_items_published ON public.ai_legal_raw_items USING btree (published_at DESC NULLS LAST);

CREATE INDEX idx_ai_legal_raw_items_regulation ON public.ai_legal_raw_items USING btree (regulation_id) WHERE (regulation_id IS NOT NULL);

CREATE INDEX idx_ai_legal_raw_items_source ON public.ai_legal_raw_items USING btree (source_id);

CREATE INDEX idx_ai_legal_raw_items_status ON public.ai_legal_raw_items USING btree (triage_status);

CREATE INDEX idx_ai_legal_source_mentions_fetched ON public.ai_legal_source_mentions USING btree (fetched_at);

CREATE INDEX idx_ai_legal_source_mentions_host ON public.ai_legal_source_mentions USING btree (host);

CREATE INDEX idx_ai_legal_source_mentions_pub ON public.ai_legal_source_mentions USING btree (published_at DESC NULLS LAST);

CREATE INDEX idx_ai_legal_source_mentions_status ON public.ai_legal_source_mentions USING btree (http_status);

CREATE INDEX idx_ai_legal_source_mentions_subject ON public.ai_legal_source_mentions USING btree (subject_kind, subject_id);

CREATE INDEX idx_ai_legal_source_runs_source ON public.ai_legal_source_runs USING btree (source_id, started_at DESC);

CREATE INDEX idx_ai_legal_source_runs_status ON public.ai_legal_source_runs USING btree (status);

CREATE INDEX idx_ai_legal_sources_active ON public.ai_legal_sources USING btree (active);

CREATE INDEX idx_ai_legal_sources_kind ON public.ai_legal_sources USING btree (kind);

CREATE INDEX idx_ai_legal_sources_last_run ON public.ai_legal_sources USING btree (last_run_at NULLS FIRST) WHERE (active = true);

CREATE INDEX idx_ai_legal_sources_tags ON public.ai_legal_sources USING gin (tags);

CREATE INDEX idx_ai_legal_user_submissions_created ON public.ai_legal_user_submissions USING btree (created_at DESC);

CREATE INDEX idx_ai_legal_user_submissions_status ON public.ai_legal_user_submissions USING btree (status);

CREATE INDEX idx_ai_regulations_affected_sectors ON public.ai_regulations USING gin (affected_sectors);

CREATE INDEX idx_ai_regulations_effective_date ON public.ai_regulations USING btree (effective_date DESC NULLS LAST);

CREATE INDEX idx_ai_regulations_enforcement_date ON public.ai_regulations USING btree (enforcement_date DESC NULLS LAST);

CREATE INDEX idx_ai_regulations_importance ON public.ai_regulations USING btree (importance_score DESC NULLS LAST);

CREATE INDEX idx_ai_regulations_jurisdiction ON public.ai_regulations USING btree (jurisdiction);

CREATE INDEX idx_ai_regulations_key_provisions ON public.ai_regulations USING gin (key_provisions);

CREATE INDEX idx_ai_regulations_regulation_type ON public.ai_regulations USING btree (regulation_type);

CREATE INDEX idx_ai_regulations_scope ON public.ai_regulations USING gin (scope);

CREATE INDEX idx_ai_regulations_search_tsv ON public.ai_regulations USING gin (search_tsv);

CREATE UNIQUE INDEX idx_ai_regulations_short_name_jurisdiction ON public.ai_regulations USING btree (short_name, jurisdiction);

CREATE INDEX idx_ai_regulations_status ON public.ai_regulations USING btree (status);

CREATE INDEX idx_ai_regulations_tags ON public.ai_regulations USING gin (tags);

CREATE INDEX idx_api_keys_active ON public.ai_legal_api_keys USING btree (revoked_at) WHERE (revoked_at IS NULL);

CREATE INDEX idx_api_keys_prefix ON public.ai_legal_api_keys USING btree (key_prefix);

CREATE INDEX tracker_idx_assessment_questions_sector ON public.tracker_assessment_questions USING btree (sector_id);

CREATE INDEX tracker_idx_cohort_courses_cohort ON public.tracker_cohort_courses USING btree (cohort_id);

CREATE INDEX tracker_idx_cohort_courses_course ON public.tracker_cohort_courses USING btree (course_id);

CREATE INDEX tracker_idx_cohort_organisations_cohort ON public.tracker_cohort_organisations USING btree (cohort_id);

CREATE INDEX tracker_idx_cohort_organisations_org ON public.tracker_cohort_organisations USING btree (organisation_id);

CREATE INDEX tracker_idx_cohort_participants_cohort ON public.tracker_cohort_participants USING btree (cohort_id);

CREATE UNIQUE INDEX tracker_idx_cohort_participants_unique ON public.tracker_cohort_participants USING btree (cohort_id, contact_id);

CREATE INDEX tracker_idx_cohort_sessions_cohort ON public.tracker_cohort_sessions USING btree (cohort_id);

CREATE INDEX tracker_idx_cohorts_organisation ON public.tracker_cohorts USING btree (client_organisation_id);

CREATE INDEX tracker_idx_cohorts_sector ON public.tracker_cohorts USING btree (sector_id);

CREATE INDEX tracker_idx_cohorts_trainer ON public.tracker_cohorts USING btree (trainer_id);

CREATE INDEX tracker_idx_contacts_organisation ON public.tracker_contacts USING btree (organisation_id);

CREATE INDEX tracker_idx_contacts_sector ON public.tracker_contacts USING btree (sector_id);

CREATE INDEX tracker_idx_course_modules_course ON public.tracker_course_modules USING btree (course_id);

CREATE INDEX tracker_idx_courses_sector ON public.tracker_courses USING btree (sector_id);

CREATE INDEX tracker_idx_document_templates_sector ON public.tracker_document_templates USING btree (sector_id);

CREATE INDEX tracker_idx_engagement_milestones_engagement ON public.tracker_engagement_milestones USING btree (engagement_id);

CREATE INDEX tracker_idx_engagement_sessions_engagement ON public.tracker_engagement_sessions USING btree (engagement_id);

CREATE INDEX tracker_idx_feedback_status ON public.tracker_feedback USING btree (status);

CREATE INDEX tracker_idx_funding_applications_opportunity ON public.tracker_funding_applications USING btree (opportunity_id);

CREATE INDEX tracker_idx_funding_opportunities_funder ON public.tracker_funding_opportunities USING btree (funder_id);

CREATE INDEX tracker_idx_funding_opportunities_sector ON public.tracker_funding_opportunities USING btree (sector_id);

CREATE INDEX tracker_idx_funding_opportunities_stage ON public.tracker_funding_opportunities USING btree (pipeline_stage);

CREATE INDEX tracker_idx_funding_reports_application ON public.tracker_funding_reports USING btree (application_id);

CREATE INDEX tracker_idx_generated_documents_organisation ON public.tracker_generated_documents USING btree (organisation_id);

CREATE INDEX tracker_idx_generated_documents_sector ON public.tracker_generated_documents USING btree (sector_id);

CREATE UNIQUE INDEX tracker_idx_gmail_tokens_email ON public.tracker_gmail_tokens USING btree (user_email);

CREATE INDEX tracker_idx_intelligence_active ON public.tracker_industry_intelligence USING btree (is_active, category);

CREATE INDEX tracker_idx_intelligence_category ON public.tracker_industry_intelligence USING btree (category);

CREATE INDEX tracker_idx_intelligence_embedding ON public.tracker_industry_intelligence USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX tracker_idx_intelligence_sector ON public.tracker_industry_intelligence USING btree (sector_id);

CREATE INDEX tracker_idx_intelligence_text ON public.tracker_industry_intelligence USING gin (to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE(summary, ''::text))));

CREATE INDEX tracker_idx_job_runs_job ON public.tracker_job_runs USING btree (job_id);

CREATE INDEX tracker_idx_job_runs_started ON public.tracker_job_runs USING btree (started_at DESC);

CREATE INDEX tracker_idx_knowledge_active ON public.tracker_knowledge_entries USING btree (is_active, category);

CREATE INDEX tracker_idx_knowledge_category ON public.tracker_knowledge_entries USING btree (category);

CREATE INDEX tracker_idx_knowledge_course ON public.tracker_knowledge_entries USING btree (course_id);

CREATE INDEX tracker_idx_knowledge_embedding ON public.tracker_knowledge_entries USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX tracker_idx_knowledge_org ON public.tracker_knowledge_entries USING btree (organisation_id);

CREATE INDEX tracker_idx_knowledge_sector ON public.tracker_knowledge_entries USING btree (sector_id);

CREATE INDEX tracker_idx_knowledge_source ON public.tracker_knowledge_entries USING btree (source_type, source_id);

CREATE INDEX tracker_idx_knowledge_tags_knowledge ON public.tracker_knowledge_tags USING btree (knowledge_id);

CREATE INDEX tracker_idx_knowledge_tags_tag ON public.tracker_knowledge_tags USING btree (tag);

CREATE UNIQUE INDEX tracker_idx_knowledge_tags_unique ON public.tracker_knowledge_tags USING btree (knowledge_id, tag);

CREATE INDEX tracker_idx_knowledge_text ON public.tracker_knowledge_entries USING gin (to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE(content, ''::text))));

CREATE INDEX idx_lawsuit_events_date ON public.ai_lawsuit_events USING btree (event_date DESC NULLS LAST);

CREATE INDEX idx_lawsuit_events_lawsuit_id ON public.ai_lawsuit_events USING btree (lawsuit_id);

CREATE INDEX tracker_idx_learning_journeys_contact ON public.tracker_learning_journeys USING btree (contact_id);

CREATE INDEX tracker_idx_learning_journeys_organisation ON public.tracker_learning_journeys USING btree (organisation_id);

CREATE INDEX tracker_idx_learning_outcomes_course ON public.tracker_learning_outcomes USING btree (course_id);

CREATE INDEX tracker_idx_learning_tasks_cohort ON public.tracker_learning_tasks USING btree (cohort_id);

CREATE INDEX tracker_idx_learning_tasks_contact ON public.tracker_learning_tasks USING btree (contact_id);

CREATE INDEX tracker_idx_learning_tasks_outcome ON public.tracker_learning_tasks USING btree (outcome_id);

CREATE INDEX tracker_idx_learning_tasks_status ON public.tracker_learning_tasks USING btree (status);

CREATE UNIQUE INDEX idx_legal_notifs_dedup ON public.ai_legal_notifications USING btree (subscription_id, event_id);

CREATE INDEX idx_legal_notifs_queued ON public.ai_legal_notifications USING btree (created_at) WHERE ((status)::text = 'queued'::text);

CREATE INDEX idx_legal_subs_active ON public.ai_legal_subscriptions USING btree (entity_kind, entity_id) WHERE ((confirmed_at IS NOT NULL) AND (unsubscribed_at IS NULL));

CREATE INDEX idx_legal_subs_confirm_token ON public.ai_legal_subscriptions USING btree (confirm_token);

CREATE INDEX idx_legal_subs_email ON public.ai_legal_subscriptions USING btree (lower((email)::text));

CREATE UNIQUE INDEX idx_legal_subs_unique ON public.ai_legal_subscriptions USING btree (lower((email)::text), entity_kind, COALESCE(entity_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE (unsubscribed_at IS NULL);

CREATE INDEX idx_legal_subs_unsubscribe_token ON public.ai_legal_subscriptions USING btree (unsubscribe_token);

CREATE INDEX tracker_idx_needs_assessments_organisation ON public.tracker_needs_assessments USING btree (organisation_id);

CREATE INDEX tracker_idx_needs_assessments_sector ON public.tracker_needs_assessments USING btree (sector_id);

CREATE INDEX tracker_idx_newsletter_curriculum ON public.tracker_newsletter_items USING btree (is_curriculum_relevant);

CREATE INDEX tracker_idx_newsletter_digest ON public.tracker_newsletter_items USING btree (digest_date);

CREATE INDEX tracker_idx_newsletter_digests_date ON public.tracker_newsletter_digests USING btree (digest_date DESC);

CREATE UNIQUE INDEX tracker_idx_newsletter_gmail_id ON public.tracker_newsletter_items USING btree (gmail_message_id);

CREATE INDEX tracker_idx_newsletter_received ON public.tracker_newsletter_items USING btree (received_at DESC);

CREATE INDEX tracker_idx_notifications_unread ON public.tracker_notifications USING btree (user_id, is_read) WHERE (is_read = false);

CREATE INDEX tracker_idx_notifications_user ON public.tracker_notifications USING btree (user_id);

CREATE INDEX tracker_idx_organisations_funder ON public.tracker_organisations USING btree (funder_organisation_id);

CREATE INDEX tracker_idx_organisations_relationship_type ON public.tracker_organisations USING btree (relationship_type);

CREATE INDEX tracker_idx_organisations_sector ON public.tracker_organisations USING btree (sector_id);

CREATE INDEX tracker_idx_outreach_campaigns_sector ON public.tracker_outreach_campaigns USING btree (sector_id);

CREATE INDEX tracker_idx_outreach_messages_campaign ON public.tracker_outreach_messages USING btree (campaign_id);

CREATE INDEX tracker_idx_outreach_messages_contact ON public.tracker_outreach_messages USING btree (contact_id);

CREATE INDEX tracker_idx_participant_tokens_contact ON public.tracker_participant_tokens USING btree (contact_id);

CREATE UNIQUE INDEX tracker_idx_participant_tokens_token ON public.tracker_participant_tokens USING btree (token);

CREATE INDEX idx_regulation_events_date ON public.ai_regulation_events USING btree (event_date DESC NULLS LAST);

CREATE INDEX idx_regulation_events_regulation_id ON public.ai_regulation_events USING btree (regulation_id);

CREATE INDEX tracker_idx_service_engagements_organisation ON public.tracker_service_engagements USING btree (organisation_id);

CREATE INDEX tracker_idx_service_engagements_sector ON public.tracker_service_engagements USING btree (sector_id);

CREATE INDEX tracker_idx_social_posts_sector ON public.tracker_social_posts USING btree (sector_id);

CREATE INDEX idx_tools_category ON public.ai_legal_tools USING btree (category);

CREATE INDEX idx_tools_kind ON public.ai_legal_tools USING btree (kind);

CREATE INDEX idx_tools_pricing ON public.ai_legal_tools USING btree (pricing);

CREATE INDEX idx_tools_tags ON public.ai_legal_tools USING gin (tags);

CREATE INDEX idx_tools_vendor ON public.ai_legal_tools USING btree (vendor);

CREATE INDEX tracker_idx_uploaded_documents_entity ON public.tracker_uploaded_documents USING btree (entity_type, entity_id);

CREATE INDEX tracker_idx_uploaded_documents_sector ON public.tracker_uploaded_documents USING btree (sector_id);

CREATE INDEX idx_usecases_categories ON public.ai_legal_usecases USING gin (categories);

CREATE INDEX idx_usecases_firm ON public.ai_legal_usecases USING btree (firm_name);

CREATE INDEX idx_usecases_firm_type ON public.ai_legal_usecases USING btree (firm_type);

CREATE INDEX idx_usecases_jurisdiction ON public.ai_legal_usecases USING btree (jurisdiction);

CREATE INDEX idx_usecases_published ON public.ai_legal_usecases USING btree (published_at DESC NULLS LAST);

CREATE INDEX idx_usecases_tags ON public.ai_legal_usecases USING gin (tags);

CREATE INDEX idx_usecases_tools_used ON public.ai_legal_usecases USING gin (tools_used);

CREATE INDEX tracker_newsletter_items_source_type_idx ON public.tracker_newsletter_items USING btree (source_type);

ALTER TABLE ONLY public.tracker_agent_conversations
    ADD CONSTRAINT tracker_agent_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_ai_conversations
    ADD CONSTRAINT tracker_ai_conversations_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.tracker_courses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_ai_conversations
    ADD CONSTRAINT tracker_ai_conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_ai_interactions
    ADD CONSTRAINT tracker_ai_interactions_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_ai_interactions
    ADD CONSTRAINT tracker_ai_interactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.ai_lawsuit_events
    ADD CONSTRAINT ai_lawsuit_events_lawsuit_id_fkey FOREIGN KEY (lawsuit_id) REFERENCES public.ai_lawsuits(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_notifications
    ADD CONSTRAINT ai_legal_notifications_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.ai_legal_subscriptions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_lawsuit_id_fkey FOREIGN KEY (lawsuit_id) REFERENCES public.ai_lawsuits(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_regulation_id_fkey FOREIGN KEY (regulation_id) REFERENCES public.ai_regulations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.ai_legal_sources(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_source_runs
    ADD CONSTRAINT ai_legal_source_runs_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.ai_legal_sources(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_user_submissions
    ADD CONSTRAINT ai_legal_user_submissions_promoted_to_lawsuit_id_fkey FOREIGN KEY (promoted_to_lawsuit_id) REFERENCES public.ai_lawsuits(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_legal_user_submissions
    ADD CONSTRAINT ai_legal_user_submissions_promoted_to_regulation_id_fkey FOREIGN KEY (promoted_to_regulation_id) REFERENCES public.ai_regulations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_regulation_events
    ADD CONSTRAINT ai_regulation_events_regulation_id_fkey FOREIGN KEY (regulation_id) REFERENCES public.ai_regulations(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_assessment_questions
    ADD CONSTRAINT tracker_assessment_questions_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_cohort_courses
    ADD CONSTRAINT tracker_cohort_courses_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.tracker_cohorts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_cohort_courses
    ADD CONSTRAINT tracker_cohort_courses_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.tracker_courses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_cohort_organisations
    ADD CONSTRAINT tracker_cohort_organisations_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.tracker_cohorts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_cohort_organisations
    ADD CONSTRAINT tracker_cohort_organisations_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_cohort_participants
    ADD CONSTRAINT tracker_cohort_participants_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.tracker_cohorts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_cohort_participants
    ADD CONSTRAINT tracker_cohort_participants_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_cohort_sessions
    ADD CONSTRAINT tracker_cohort_sessions_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.tracker_cohorts(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_cohorts
    ADD CONSTRAINT tracker_cohorts_organisation_id_fkey FOREIGN KEY (client_organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_cohorts
    ADD CONSTRAINT tracker_cohorts_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_cohorts
    ADD CONSTRAINT tracker_cohorts_trainer_id_fkey FOREIGN KEY (trainer_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_contacts
    ADD CONSTRAINT tracker_contacts_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_contacts
    ADD CONSTRAINT tracker_contacts_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_course_modules
    ADD CONSTRAINT tracker_course_modules_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.tracker_courses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_courses
    ADD CONSTRAINT tracker_courses_last_updated_by_fkey FOREIGN KEY (last_updated_by) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_courses
    ADD CONSTRAINT tracker_courses_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_document_templates
    ADD CONSTRAINT tracker_document_templates_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_engagement_milestones
    ADD CONSTRAINT tracker_engagement_milestones_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.tracker_service_engagements(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_engagement_sessions
    ADD CONSTRAINT tracker_engagement_sessions_engagement_id_fkey FOREIGN KEY (engagement_id) REFERENCES public.tracker_service_engagements(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_feedback
    ADD CONSTRAINT tracker_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_funding_applications
    ADD CONSTRAINT tracker_funding_applications_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_funding_applications
    ADD CONSTRAINT tracker_funding_applications_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.tracker_funding_opportunities(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_funding_opportunities
    ADD CONSTRAINT tracker_funding_opportunities_funder_id_fkey FOREIGN KEY (funder_id) REFERENCES public.tracker_funders(id);

ALTER TABLE ONLY public.tracker_funding_opportunities
    ADD CONSTRAINT tracker_funding_opportunities_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_funding_reports
    ADD CONSTRAINT tracker_funding_reports_application_id_fkey FOREIGN KEY (application_id) REFERENCES public.tracker_funding_applications(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_generated_documents
    ADD CONSTRAINT tracker_generated_documents_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.tracker_needs_assessments(id);

ALTER TABLE ONLY public.tracker_generated_documents
    ADD CONSTRAINT tracker_generated_documents_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_generated_documents
    ADD CONSTRAINT tracker_generated_documents_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_generated_documents
    ADD CONSTRAINT tracker_generated_documents_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_generated_documents
    ADD CONSTRAINT tracker_generated_documents_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.tracker_document_templates(id);

ALTER TABLE ONLY public.tracker_industry_intelligence
    ADD CONSTRAINT tracker_industry_intelligence_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_industry_intelligence
    ADD CONSTRAINT tracker_industry_intelligence_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_job_runs
    ADD CONSTRAINT tracker_job_runs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.tracker_background_jobs(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_knowledge_entries
    ADD CONSTRAINT tracker_knowledge_entries_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.tracker_courses(id);

ALTER TABLE ONLY public.tracker_knowledge_entries
    ADD CONSTRAINT tracker_knowledge_entries_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_knowledge_entries
    ADD CONSTRAINT tracker_knowledge_entries_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_knowledge_tags
    ADD CONSTRAINT tracker_knowledge_tags_knowledge_id_fkey FOREIGN KEY (knowledge_id) REFERENCES public.tracker_knowledge_entries(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_learning_journeys
    ADD CONSTRAINT tracker_learning_journeys_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_learning_journeys
    ADD CONSTRAINT tracker_learning_journeys_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_learning_journeys
    ADD CONSTRAINT tracker_learning_journeys_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_learning_outcomes
    ADD CONSTRAINT tracker_learning_outcomes_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.tracker_courses(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.tracker_learning_outcomes
    ADD CONSTRAINT tracker_learning_outcomes_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.tracker_course_modules(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.tracker_learning_tasks
    ADD CONSTRAINT tracker_learning_tasks_cohort_id_fkey FOREIGN KEY (cohort_id) REFERENCES public.tracker_cohorts(id);

ALTER TABLE ONLY public.tracker_learning_tasks
    ADD CONSTRAINT tracker_learning_tasks_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_learning_tasks
    ADD CONSTRAINT tracker_learning_tasks_outcome_id_fkey FOREIGN KEY (outcome_id) REFERENCES public.tracker_learning_outcomes(id);

ALTER TABLE ONLY public.tracker_learning_tasks
    ADD CONSTRAINT tracker_learning_tasks_participant_id_fkey FOREIGN KEY (participant_id) REFERENCES public.tracker_cohort_participants(id);

ALTER TABLE ONLY public.tracker_learning_tasks
    ADD CONSTRAINT tracker_learning_tasks_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_needs_assessments
    ADD CONSTRAINT tracker_needs_assessments_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_needs_assessments
    ADD CONSTRAINT tracker_needs_assessments_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_needs_assessments
    ADD CONSTRAINT tracker_needs_assessments_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_notifications
    ADD CONSTRAINT tracker_notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_organisations
    ADD CONSTRAINT tracker_organisations_funder_organisation_id_fkey FOREIGN KEY (funder_organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_organisations
    ADD CONSTRAINT tracker_organisations_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_outreach_campaigns
    ADD CONSTRAINT tracker_outreach_campaigns_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_outreach_messages
    ADD CONSTRAINT tracker_outreach_messages_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.tracker_outreach_campaigns(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.tracker_outreach_messages
    ADD CONSTRAINT tracker_outreach_messages_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_participant_tokens
    ADD CONSTRAINT tracker_participant_tokens_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.tracker_needs_assessments(id);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.tracker_contacts(id);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.tracker_generated_documents(id);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.tracker_team_members(id);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_organisation_id_fkey FOREIGN KEY (organisation_id) REFERENCES public.tracker_organisations(id);

ALTER TABLE ONLY public.tracker_service_engagements
    ADD CONSTRAINT tracker_service_engagements_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_social_posts
    ADD CONSTRAINT tracker_social_posts_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_uploaded_documents
    ADD CONSTRAINT tracker_uploaded_documents_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.tracker_sectors(id);

ALTER TABLE ONLY public.tracker_uploaded_documents
    ADD CONSTRAINT tracker_uploaded_documents_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.tracker_team_members(id);


-- ─── Functions: full-text-search maintenance + event fan-out ───

CREATE FUNCTION public.ai_lawsuits_search_tsv_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.search_tsv :=
    setweight(to_tsvector('english', coalesce(NEW.case_name, '')), 'A') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.plaintiffs, '{}'), ' ')), 'B') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.defendants, '{}'), ' ')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.summary, '')), 'C') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.key_issues, '{}'), ' ')), 'D');
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.ai_regulations_search_tsv_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.search_tsv :=
    setweight(to_tsvector('english', coalesce(NEW.regulation_name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.short_name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.jurisdiction, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.regulator, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.summary, '')), 'C') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.key_provisions, '{}'), ' ')), 'D');
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.fanout_lawsuit_event_notifications() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO ai_legal_notifications (subscription_id, event_kind, event_id, status)
  SELECT s.id, 'lawsuit_event', NEW.id, 'queued'
    FROM ai_legal_subscriptions s
   WHERE s.confirmed_at IS NOT NULL
     AND s.unsubscribed_at IS NULL
     AND s.entity_kind = 'lawsuit'
     AND s.entity_id = NEW.lawsuit_id
   ON CONFLICT (subscription_id, event_id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.fanout_regulation_event_notifications() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO ai_legal_notifications (subscription_id, event_kind, event_id, status)
  SELECT s.id, 'regulation_event', NEW.id, 'queued'
    FROM ai_legal_subscriptions s
   WHERE s.confirmed_at IS NOT NULL
     AND s.unsubscribed_at IS NULL
     AND s.entity_kind = 'regulation'
     AND s.entity_id = NEW.regulation_id
   ON CONFLICT (subscription_id, event_id) DO NOTHING;
  RETURN NEW;
END;
$$;


-- ─── Triggers ───

CREATE TRIGGER ai_lawsuits_search_tsv_update BEFORE INSERT OR UPDATE OF case_name, plaintiffs, defendants, summary, key_issues ON public.ai_lawsuits FOR EACH ROW EXECUTE FUNCTION public.ai_lawsuits_search_tsv_trigger();

CREATE TRIGGER ai_regulations_search_tsv_update BEFORE INSERT OR UPDATE OF regulation_name, short_name, jurisdiction, regulator, summary, key_provisions ON public.ai_regulations FOR EACH ROW EXECUTE FUNCTION public.ai_regulations_search_tsv_trigger();

CREATE TRIGGER trg_fanout_lawsuit_events AFTER INSERT ON public.ai_lawsuit_events FOR EACH ROW EXECUTE FUNCTION public.fanout_lawsuit_event_notifications();

CREATE TRIGGER trg_fanout_regulation_events AFTER INSERT ON public.ai_regulation_events FOR EACH ROW EXECUTE FUNCTION public.fanout_regulation_event_notifications();
