-- 039_tracker_import.sql
-- GENERATED by scripts/tracker/build-import.js from the Tracker app pg_dump.
-- Do not edit by hand — re-run the generator. Source of truth: the dump.
--
-- DECIDED SCOPE (2026-05-25): only the AI-Legal Tracker + ingestion is imported.
-- AI-Legal core tables as-is; the industry-intelligence feed prefixed tracker_;
-- the CRM/cohort/training, outreach, fundraising, ai-assistant and auth/infra
-- tables are dropped (covered by grounded or out of scope). FKs to dropped
-- tables are stripped. OWNER/GRANT/COMMENT/data stripped. FTS + fan-out
-- functions/triggers appended at the end (they reference only kept tables).
-- Data loads separately (one-shot): node scripts/tracker/build-import.js --data
-- Tables: 16 (15 as-is, 1 prefixed).

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.ai_lawsuit_events (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    lawsuit_id uuid NOT NULL,
    event_date date,
    event_type character varying(50) DEFAULT 'update'::character varying NOT NULL,
    title character varying(500),
    description text,
    source_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_verified_at timestamp with time zone
);

CREATE TABLE public.ai_lawsuits (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    case_name character varying(500) NOT NULL,
    plaintiffs text[] DEFAULT '{}'::text[],
    defendants text[] DEFAULT '{}'::text[],
    court character varying(300),
    judge character varying(200),
    jurisdiction character varying(100),
    district character varying(200),
    circuit character varying(100),
    status character varying(50) DEFAULT 'active'::character varying,
    case_type character varying(100) DEFAULT 'copyright'::character varying,
    key_issues text[] DEFAULT '{}'::text[],
    filing_date date,
    last_update date,
    next_deadline date,
    next_deadline_notes text,
    outcome text,
    settlement_amount character varying(200),
    case_url text,
    source_url text,
    summary text,
    curriculum_relevance text,
    is_curriculum_relevant boolean DEFAULT true,
    tags text[] DEFAULT '{}'::text[],
    external_id character varying(200),
    last_scraped_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    detailed_analysis text,
    knowledge_entry_id uuid,
    analysis_generated_at timestamp with time zone,
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    search_tsv tsvector,
    importance_score numeric(5,2),
    importance_reasoning text,
    importance_signals jsonb,
    importance_scored_at timestamp with time zone
);

CREATE TABLE public.ai_legal_api_keys (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    key_hash text NOT NULL,
    key_prefix character varying(16) NOT NULL,
    owner_name character varying(200) NOT NULL,
    owner_email character varying(320),
    description text,
    tier character varying(40) DEFAULT 'free'::character varying NOT NULL,
    daily_limit integer DEFAULT 10000 NOT NULL,
    requests_today integer DEFAULT 0 NOT NULL,
    window_start date DEFAULT CURRENT_DATE NOT NULL,
    last_used_at timestamp with time zone,
    last_used_ip inet,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_insights (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    subject_kind character varying(20) NOT NULL,
    subject_id uuid NOT NULL,
    insight_type character varying(30) NOT NULL,
    content text NOT NULL,
    citations jsonb DEFAULT '[]'::jsonb NOT NULL,
    model_used character varying(100),
    confidence numeric(3,2),
    generated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_notifications (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    subscription_id uuid NOT NULL,
    event_kind character varying(20) NOT NULL,
    event_id uuid NOT NULL,
    status character varying(20) DEFAULT 'queued'::character varying NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    sent_at timestamp with time zone,
    attempt_count integer DEFAULT 0 NOT NULL,
    error_message text,
    CONSTRAINT ai_legal_notifications_event_kind_check CHECK (((event_kind)::text = ANY ((ARRAY['lawsuit_event'::character varying, 'regulation_event'::character varying])::text[]))),
    CONSTRAINT ai_legal_notifications_status_check CHECK (((status)::text = ANY ((ARRAY['queued'::character varying, 'sent'::character varying, 'failed'::character varying, 'skipped'::character varying])::text[])))
);

CREATE TABLE public.ai_legal_raw_items (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    source_id uuid NOT NULL,
    external_id text,
    url text,
    title text,
    content text,
    author text,
    published_at timestamp with time zone,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    raw_payload jsonb,
    triage_status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    triage_result jsonb,
    triaged_at timestamp with time zone,
    lawsuit_id uuid,
    regulation_id uuid,
    event_id uuid
);

CREATE TABLE public.ai_legal_source_mentions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    subject_kind character varying(20) NOT NULL,
    subject_id uuid NOT NULL,
    url text NOT NULL,
    canonical_url text,
    host character varying(300),
    title character varying(800),
    author character varying(300),
    site_name character varying(200),
    description text,
    body_excerpt text,
    image_url text,
    published_at timestamp with time zone,
    fetched_at timestamp with time zone DEFAULT now() NOT NULL,
    http_status integer,
    error text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_source_runs (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    source_id uuid NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    items_seen integer DEFAULT 0 NOT NULL,
    items_new integer DEFAULT 0 NOT NULL,
    items_duplicate integer DEFAULT 0 NOT NULL,
    status character varying(30) DEFAULT 'running'::character varying NOT NULL,
    error text
);

CREATE TABLE public.ai_legal_sources (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(300) NOT NULL,
    kind character varying(30) NOT NULL,
    url text NOT NULL,
    jurisdiction character varying(200),
    tags text[] DEFAULT '{}'::text[],
    active boolean DEFAULT true NOT NULL,
    run_frequency_hours integer DEFAULT 6 NOT NULL,
    last_run_at timestamp with time zone,
    last_success_at timestamp with time zone,
    last_error text,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    items_seen integer DEFAULT 0 NOT NULL,
    items_new integer DEFAULT 0 NOT NULL,
    items_promoted integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_subscriptions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    entity_kind character varying(20) NOT NULL,
    entity_id uuid,
    email character varying(320) NOT NULL,
    confirmed_at timestamp with time zone,
    confirm_token character varying(64) NOT NULL,
    unsubscribe_token character varying(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    unsubscribed_at timestamp with time zone,
    last_sent_at timestamp with time zone,
    CONSTRAINT ai_legal_subscriptions_check CHECK (((((entity_kind)::text = 'all'::text) AND (entity_id IS NULL)) OR (((entity_kind)::text <> 'all'::text) AND (entity_id IS NOT NULL)))),
    CONSTRAINT ai_legal_subscriptions_entity_kind_check CHECK (((entity_kind)::text = ANY ((ARRAY['lawsuit'::character varying, 'regulation'::character varying, 'all'::character varying])::text[])))
);

CREATE TABLE public.ai_legal_tools (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name character varying(300) NOT NULL,
    kind character varying(20) DEFAULT 'tool'::character varying NOT NULL,
    vendor character varying(300),
    category character varying(50),
    description text,
    url text,
    pricing character varying(30),
    strengths text,
    limitations text,
    integrations text[] DEFAULT '{}'::text[],
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    logo_url text,
    tags text[] DEFAULT '{}'::text[],
    is_published boolean DEFAULT true NOT NULL,
    verified_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_usecases (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    firm_name character varying(300) NOT NULL,
    firm_type character varying(30),
    jurisdiction character varying(200),
    use_case_title character varying(500) NOT NULL,
    summary text,
    tools_used text[] DEFAULT '{}'::text[],
    categories text[] DEFAULT '{}'::text[],
    outcome text,
    quantified_impact character varying(500),
    source_url text NOT NULL,
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    source_name character varying(300),
    author character varying(300),
    published_at timestamp with time zone,
    verified_at timestamp with time zone,
    tags text[] DEFAULT '{}'::text[],
    is_published boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_legal_user_submissions (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    submission_kind character varying(20) DEFAULT 'lawsuit'::character varying NOT NULL,
    case_name character varying(500),
    jurisdiction character varying(200),
    parties text,
    source_url text NOT NULL,
    summary text,
    submitter_email character varying(300),
    submitter_ip character varying(45),
    submitter_ua text,
    status character varying(30) DEFAULT 'pending'::character varying NOT NULL,
    review_notes text,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    promoted_to_lawsuit_id uuid,
    promoted_to_regulation_id uuid,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.ai_regulation_events (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    regulation_id uuid NOT NULL,
    event_date date,
    event_type character varying(50) DEFAULT 'update'::character varying NOT NULL,
    title character varying(500),
    description text,
    source_url text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    source_verified_at timestamp with time zone
);

CREATE TABLE public.ai_regulations (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    regulation_name character varying(500) NOT NULL,
    short_name character varying(200),
    jurisdiction character varying(200) NOT NULL,
    regulator character varying(300),
    status character varying(50) DEFAULT 'in_force'::character varying,
    regulation_type character varying(100),
    scope text[] DEFAULT '{}'::text[],
    affected_sectors text[] DEFAULT '{}'::text[],
    proposed_date date,
    enacted_date date,
    effective_date date,
    enforcement_date date,
    next_milestone date,
    next_milestone_notes text,
    key_provisions text[] DEFAULT '{}'::text[],
    penalties text,
    extraterritorial_scope text,
    official_url text,
    source_url text,
    source_urls text[] DEFAULT '{}'::text[] NOT NULL,
    summary text,
    detailed_analysis text,
    analysis_generated_at timestamp with time zone,
    curriculum_relevance text,
    is_curriculum_relevant boolean DEFAULT true,
    tags text[] DEFAULT '{}'::text[],
    knowledge_entry_id uuid,
    external_id character varying(200),
    last_scraped_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    search_tsv tsvector,
    importance_score numeric(5,2),
    importance_reasoning text,
    importance_signals jsonb,
    importance_scored_at timestamp with time zone
);

CREATE TABLE public.tracker_industry_intelligence (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    sector_id uuid,
    category character varying(100) NOT NULL,
    title character varying(500) NOT NULL,
    summary text NOT NULL,
    details text,
    source character varying(500),
    source_url character varying(1000),
    relevance_score numeric(3,2),
    is_actionable boolean DEFAULT false,
    action_taken text,
    reviewed_by uuid,
    reviewed_at timestamp with time zone,
    discovered_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    is_active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    embedding public.vector(384)
);

ALTER TABLE ONLY public.ai_lawsuit_events
    ADD CONSTRAINT ai_lawsuit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_lawsuits
    ADD CONSTRAINT ai_lawsuits_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_api_keys
    ADD CONSTRAINT ai_legal_api_keys_key_hash_key UNIQUE (key_hash);

ALTER TABLE ONLY public.ai_legal_api_keys
    ADD CONSTRAINT ai_legal_api_keys_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_insights
    ADD CONSTRAINT ai_legal_insights_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_insights
    ADD CONSTRAINT ai_legal_insights_unique UNIQUE (subject_kind, subject_id, insight_type);

ALTER TABLE ONLY public.ai_legal_notifications
    ADD CONSTRAINT ai_legal_notifications_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_dedup UNIQUE (source_id, external_id);

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_source_mentions
    ADD CONSTRAINT ai_legal_source_mentions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_source_mentions
    ADD CONSTRAINT ai_legal_source_mentions_unique UNIQUE (subject_kind, subject_id, url);

ALTER TABLE ONLY public.ai_legal_source_runs
    ADD CONSTRAINT ai_legal_source_runs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_sources
    ADD CONSTRAINT ai_legal_sources_kind_url_uniq UNIQUE (kind, url);

ALTER TABLE ONLY public.ai_legal_sources
    ADD CONSTRAINT ai_legal_sources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_subscriptions
    ADD CONSTRAINT ai_legal_subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_tools
    ADD CONSTRAINT ai_legal_tools_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_tools
    ADD CONSTRAINT ai_legal_tools_unique UNIQUE (kind, name);

ALTER TABLE ONLY public.ai_legal_usecases
    ADD CONSTRAINT ai_legal_usecases_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_legal_user_submissions
    ADD CONSTRAINT ai_legal_user_submissions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_regulation_events
    ADD CONSTRAINT ai_regulation_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_regulations
    ADD CONSTRAINT ai_regulations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tracker_industry_intelligence
    ADD CONSTRAINT tracker_industry_intelligence_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX idx_ai_lawsuits_case_name ON public.ai_lawsuits USING btree (case_name);

CREATE INDEX idx_ai_lawsuits_case_type ON public.ai_lawsuits USING btree (case_type);

CREATE INDEX idx_ai_lawsuits_defendants ON public.ai_lawsuits USING gin (defendants);

CREATE INDEX idx_ai_lawsuits_filing_date ON public.ai_lawsuits USING btree (filing_date DESC NULLS LAST);

CREATE INDEX idx_ai_lawsuits_importance ON public.ai_lawsuits USING btree (importance_score DESC NULLS LAST);

CREATE INDEX idx_ai_lawsuits_jurisdiction ON public.ai_lawsuits USING btree (jurisdiction);

CREATE INDEX idx_ai_lawsuits_key_issues ON public.ai_lawsuits USING gin (key_issues);

CREATE INDEX idx_ai_lawsuits_last_update ON public.ai_lawsuits USING btree (last_update DESC NULLS LAST);

CREATE INDEX idx_ai_lawsuits_plaintiffs ON public.ai_lawsuits USING gin (plaintiffs);

CREATE INDEX idx_ai_lawsuits_search_tsv ON public.ai_lawsuits USING gin (search_tsv);

CREATE INDEX idx_ai_lawsuits_status ON public.ai_lawsuits USING btree (status);

CREATE INDEX idx_ai_lawsuits_tags ON public.ai_lawsuits USING gin (tags);

CREATE INDEX idx_ai_lawsuits_updated ON public.ai_lawsuits USING btree (updated_at DESC);

CREATE INDEX idx_ai_legal_insights_subject ON public.ai_legal_insights USING btree (subject_kind, subject_id);

CREATE INDEX idx_ai_legal_insights_type ON public.ai_legal_insights USING btree (insight_type);

CREATE INDEX idx_ai_legal_raw_items_fetched ON public.ai_legal_raw_items USING btree (fetched_at DESC);

CREATE INDEX idx_ai_legal_raw_items_lawsuit ON public.ai_legal_raw_items USING btree (lawsuit_id) WHERE (lawsuit_id IS NOT NULL);

CREATE INDEX idx_ai_legal_raw_items_published ON public.ai_legal_raw_items USING btree (published_at DESC NULLS LAST);

CREATE INDEX idx_ai_legal_raw_items_regulation ON public.ai_legal_raw_items USING btree (regulation_id) WHERE (regulation_id IS NOT NULL);

CREATE INDEX idx_ai_legal_raw_items_source ON public.ai_legal_raw_items USING btree (source_id);

CREATE INDEX idx_ai_legal_raw_items_status ON public.ai_legal_raw_items USING btree (triage_status);

CREATE INDEX idx_ai_legal_source_mentions_fetched ON public.ai_legal_source_mentions USING btree (fetched_at);

CREATE INDEX idx_ai_legal_source_mentions_host ON public.ai_legal_source_mentions USING btree (host);

CREATE INDEX idx_ai_legal_source_mentions_pub ON public.ai_legal_source_mentions USING btree (published_at DESC NULLS LAST);

CREATE INDEX idx_ai_legal_source_mentions_status ON public.ai_legal_source_mentions USING btree (http_status);

CREATE INDEX idx_ai_legal_source_mentions_subject ON public.ai_legal_source_mentions USING btree (subject_kind, subject_id);

CREATE INDEX idx_ai_legal_source_runs_source ON public.ai_legal_source_runs USING btree (source_id, started_at DESC);

CREATE INDEX idx_ai_legal_source_runs_status ON public.ai_legal_source_runs USING btree (status);

CREATE INDEX idx_ai_legal_sources_active ON public.ai_legal_sources USING btree (active);

CREATE INDEX idx_ai_legal_sources_kind ON public.ai_legal_sources USING btree (kind);

CREATE INDEX idx_ai_legal_sources_last_run ON public.ai_legal_sources USING btree (last_run_at NULLS FIRST) WHERE (active = true);

CREATE INDEX idx_ai_legal_sources_tags ON public.ai_legal_sources USING gin (tags);

CREATE INDEX idx_ai_legal_user_submissions_created ON public.ai_legal_user_submissions USING btree (created_at DESC);

CREATE INDEX idx_ai_legal_user_submissions_status ON public.ai_legal_user_submissions USING btree (status);

CREATE INDEX idx_ai_regulations_affected_sectors ON public.ai_regulations USING gin (affected_sectors);

CREATE INDEX idx_ai_regulations_effective_date ON public.ai_regulations USING btree (effective_date DESC NULLS LAST);

CREATE INDEX idx_ai_regulations_enforcement_date ON public.ai_regulations USING btree (enforcement_date DESC NULLS LAST);

CREATE INDEX idx_ai_regulations_importance ON public.ai_regulations USING btree (importance_score DESC NULLS LAST);

CREATE INDEX idx_ai_regulations_jurisdiction ON public.ai_regulations USING btree (jurisdiction);

CREATE INDEX idx_ai_regulations_key_provisions ON public.ai_regulations USING gin (key_provisions);

CREATE INDEX idx_ai_regulations_regulation_type ON public.ai_regulations USING btree (regulation_type);

CREATE INDEX idx_ai_regulations_scope ON public.ai_regulations USING gin (scope);

CREATE INDEX idx_ai_regulations_search_tsv ON public.ai_regulations USING gin (search_tsv);

CREATE UNIQUE INDEX idx_ai_regulations_short_name_jurisdiction ON public.ai_regulations USING btree (short_name, jurisdiction);

CREATE INDEX idx_ai_regulations_status ON public.ai_regulations USING btree (status);

CREATE INDEX idx_ai_regulations_tags ON public.ai_regulations USING gin (tags);

CREATE INDEX idx_api_keys_active ON public.ai_legal_api_keys USING btree (revoked_at) WHERE (revoked_at IS NULL);

CREATE INDEX idx_api_keys_prefix ON public.ai_legal_api_keys USING btree (key_prefix);

CREATE INDEX tracker_idx_intelligence_active ON public.tracker_industry_intelligence USING btree (is_active, category);

CREATE INDEX tracker_idx_intelligence_category ON public.tracker_industry_intelligence USING btree (category);

CREATE INDEX tracker_idx_intelligence_embedding ON public.tracker_industry_intelligence USING hnsw (embedding public.vector_cosine_ops);

CREATE INDEX tracker_idx_intelligence_sector ON public.tracker_industry_intelligence USING btree (sector_id);

CREATE INDEX tracker_idx_intelligence_text ON public.tracker_industry_intelligence USING gin (to_tsvector('english'::regconfig, (((COALESCE(title, ''::character varying))::text || ' '::text) || COALESCE(summary, ''::text))));

CREATE INDEX idx_lawsuit_events_date ON public.ai_lawsuit_events USING btree (event_date DESC NULLS LAST);

CREATE INDEX idx_lawsuit_events_lawsuit_id ON public.ai_lawsuit_events USING btree (lawsuit_id);

CREATE UNIQUE INDEX idx_legal_notifs_dedup ON public.ai_legal_notifications USING btree (subscription_id, event_id);

CREATE INDEX idx_legal_notifs_queued ON public.ai_legal_notifications USING btree (created_at) WHERE ((status)::text = 'queued'::text);

CREATE INDEX idx_legal_subs_active ON public.ai_legal_subscriptions USING btree (entity_kind, entity_id) WHERE ((confirmed_at IS NOT NULL) AND (unsubscribed_at IS NULL));

CREATE INDEX idx_legal_subs_confirm_token ON public.ai_legal_subscriptions USING btree (confirm_token);

CREATE INDEX idx_legal_subs_email ON public.ai_legal_subscriptions USING btree (lower((email)::text));

CREATE UNIQUE INDEX idx_legal_subs_unique ON public.ai_legal_subscriptions USING btree (lower((email)::text), entity_kind, COALESCE(entity_id, '00000000-0000-0000-0000-000000000000'::uuid)) WHERE (unsubscribed_at IS NULL);

CREATE INDEX idx_legal_subs_unsubscribe_token ON public.ai_legal_subscriptions USING btree (unsubscribe_token);

CREATE INDEX idx_regulation_events_date ON public.ai_regulation_events USING btree (event_date DESC NULLS LAST);

CREATE INDEX idx_regulation_events_regulation_id ON public.ai_regulation_events USING btree (regulation_id);

CREATE INDEX idx_tools_category ON public.ai_legal_tools USING btree (category);

CREATE INDEX idx_tools_kind ON public.ai_legal_tools USING btree (kind);

CREATE INDEX idx_tools_pricing ON public.ai_legal_tools USING btree (pricing);

CREATE INDEX idx_tools_tags ON public.ai_legal_tools USING gin (tags);

CREATE INDEX idx_tools_vendor ON public.ai_legal_tools USING btree (vendor);

CREATE INDEX idx_usecases_categories ON public.ai_legal_usecases USING gin (categories);

CREATE INDEX idx_usecases_firm ON public.ai_legal_usecases USING btree (firm_name);

CREATE INDEX idx_usecases_firm_type ON public.ai_legal_usecases USING btree (firm_type);

CREATE INDEX idx_usecases_jurisdiction ON public.ai_legal_usecases USING btree (jurisdiction);

CREATE INDEX idx_usecases_published ON public.ai_legal_usecases USING btree (published_at DESC NULLS LAST);

CREATE INDEX idx_usecases_tags ON public.ai_legal_usecases USING gin (tags);

CREATE INDEX idx_usecases_tools_used ON public.ai_legal_usecases USING gin (tools_used);

ALTER TABLE ONLY public.ai_lawsuit_events
    ADD CONSTRAINT ai_lawsuit_events_lawsuit_id_fkey FOREIGN KEY (lawsuit_id) REFERENCES public.ai_lawsuits(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_notifications
    ADD CONSTRAINT ai_legal_notifications_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.ai_legal_subscriptions(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_lawsuit_id_fkey FOREIGN KEY (lawsuit_id) REFERENCES public.ai_lawsuits(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_regulation_id_fkey FOREIGN KEY (regulation_id) REFERENCES public.ai_regulations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_legal_raw_items
    ADD CONSTRAINT ai_legal_raw_items_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.ai_legal_sources(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_source_runs
    ADD CONSTRAINT ai_legal_source_runs_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.ai_legal_sources(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.ai_legal_user_submissions
    ADD CONSTRAINT ai_legal_user_submissions_promoted_to_lawsuit_id_fkey FOREIGN KEY (promoted_to_lawsuit_id) REFERENCES public.ai_lawsuits(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_legal_user_submissions
    ADD CONSTRAINT ai_legal_user_submissions_promoted_to_regulation_id_fkey FOREIGN KEY (promoted_to_regulation_id) REFERENCES public.ai_regulations(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.ai_regulation_events
    ADD CONSTRAINT ai_regulation_events_regulation_id_fkey FOREIGN KEY (regulation_id) REFERENCES public.ai_regulations(id) ON DELETE CASCADE;


-- ─── Functions: full-text-search maintenance + event fan-out ───

CREATE FUNCTION public.ai_lawsuits_search_tsv_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.search_tsv :=
    setweight(to_tsvector('english', coalesce(NEW.case_name, '')), 'A') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.plaintiffs, '{}'), ' ')), 'B') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.defendants, '{}'), ' ')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.summary, '')), 'C') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.key_issues, '{}'), ' ')), 'D');
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.ai_regulations_search_tsv_trigger() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  NEW.search_tsv :=
    setweight(to_tsvector('english', coalesce(NEW.regulation_name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.short_name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(NEW.jurisdiction, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.regulator, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(NEW.summary, '')), 'C') ||
    setweight(to_tsvector('english', array_to_string(coalesce(NEW.key_provisions, '{}'), ' ')), 'D');
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.fanout_lawsuit_event_notifications() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO ai_legal_notifications (subscription_id, event_kind, event_id, status)
  SELECT s.id, 'lawsuit_event', NEW.id, 'queued'
    FROM ai_legal_subscriptions s
   WHERE s.confirmed_at IS NOT NULL
     AND s.unsubscribed_at IS NULL
     AND s.entity_kind = 'lawsuit'
     AND s.entity_id = NEW.lawsuit_id
   ON CONFLICT (subscription_id, event_id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE FUNCTION public.fanout_regulation_event_notifications() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  INSERT INTO ai_legal_notifications (subscription_id, event_kind, event_id, status)
  SELECT s.id, 'regulation_event', NEW.id, 'queued'
    FROM ai_legal_subscriptions s
   WHERE s.confirmed_at IS NOT NULL
     AND s.unsubscribed_at IS NULL
     AND s.entity_kind = 'regulation'
     AND s.entity_id = NEW.regulation_id
   ON CONFLICT (subscription_id, event_id) DO NOTHING;
  RETURN NEW;
END;
$$;


-- ─── Triggers ───

CREATE TRIGGER ai_lawsuits_search_tsv_update BEFORE INSERT OR UPDATE OF case_name, plaintiffs, defendants, summary, key_issues ON public.ai_lawsuits FOR EACH ROW EXECUTE FUNCTION public.ai_lawsuits_search_tsv_trigger();

CREATE TRIGGER ai_regulations_search_tsv_update BEFORE INSERT OR UPDATE OF regulation_name, short_name, jurisdiction, regulator, summary, key_provisions ON public.ai_regulations FOR EACH ROW EXECUTE FUNCTION public.ai_regulations_search_tsv_trigger();

CREATE TRIGGER trg_fanout_lawsuit_events AFTER INSERT ON public.ai_lawsuit_events FOR EACH ROW EXECUTE FUNCTION public.fanout_lawsuit_event_notifications();

CREATE TRIGGER trg_fanout_regulation_events AFTER INSERT ON public.ai_regulation_events FOR EACH ROW EXECUTE FUNCTION public.fanout_regulation_event_notifications();
