// GET /api/learning/digests   — list recent cohort digests
// GET /api/learning/digests?latest=1 — just the most recent one with entries
//
// The cohort weekly digest powers the Home tab's masthead. Generated by
// the pg-boss handler scripts/jobs/handlers/tracker-digest.js.

import { NextResponse } from 'next/server';
import { getCurrentSession } from '@/app/lib/session';
import { pool } from '@/lib/db';

export async function GET(req: Request) {
  const session = await getCurrentSession();
  if (!session) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const url = new URL(req.url);
  const latestOnly = url.searchParams.get('latest') === '1';

  if (latestOnly) {
    const { rows } = await pool.query(
      `SELECT id, period_start, period_end, summary_md, top_entry_ids,
              entry_count, generated_at
         FROM tracker_digests
        WHERE newsroom_id IS NULL
     ORDER BY period_end DESC
        LIMIT 1`
    );
    if (rows.length === 0) return NextResponse.json({ digest: null });
    const digest = rows[0];
    let topEntries: any[] = [];
    if (Array.isArray(digest.top_entry_ids) && digest.top_entry_ids.length > 0) {
      const entries = await pool.query(
        `SELECT id, title, kind, severity, source_publisher, source_url, published_at
           FROM learning_updates
          WHERE id = ANY($1::uuid[]) AND status = 'live'
            AND (newsroom_id IS NULL OR newsroom_id = $2)`,
        [digest.top_entry_ids, session.newsroomId]
      );
      topEntries = entries.rows;
    }
    return NextResponse.json({ digest, top_entries: topEntries });
  }

  const { rows } = await pool.query(
    `SELECT id, period_start, period_end, summary_md, entry_count,
            generated_at, generated_by_model, cost_usd
       FROM tracker_digests
      WHERE newsroom_id IS NULL
   ORDER BY period_end DESC
      LIMIT 20`
  );
  return NextResponse.json({ digests: rows });
}
