// AppliancePanel — V2 Step 6.
//
// Admin-only sub-section on the /team page. Lets the admin register a
// newsroom appliance, see whether it's online, test-dispatch a no-op,
// pause / resume / delete it.

'use client';

import { useEffect, useState, FormEvent } from 'react';

type Appliance = {
  id: string;
  newsroom_id: string;
  display_name: string;
  dispatch_url: string;
  status: 'active' | 'paused' | 'failed';
  last_seen_at: string | null;
  last_seen_version: string | null;
  registered_at: string;
  registered_by_email: string | null;
};

type Health = {
  appliance: Appliance;
  recent_dispatches: Array<{
    id: string; endpoint: string; agent_slug: string | null;
    status: string; http_status: number | null; duration_ms: number | null;
    dispatched_at: string; responded_at: string | null; error: string | null;
  }>;
  last_7_days: { completed: number; failed: number; timeout: number; in_flight: number };
  online: boolean;
};

export default function AppliancePanel() {
  const [list, setList] = useState<Appliance[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showRegister, setShowRegister] = useState(false);
  const [secretReveal, setSecretReveal] = useState<{ id: string; secret: string } | null>(null);

  async function load() {
    setError(null);
    try {
      const res = await fetch('/api/appliances');
      const j = await res.json();
      if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`);
      setList(j.appliances);
    } catch (e: any) {
      setError(e.message);
    }
  }
  useEffect(() => { load(); }, []);

  const appliance = list && list[0];

  return (
    <section style={{ marginTop: 28, paddingTop: 18, borderTop: '1px solid #e5e5e5' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
        <h2 style={{ fontSize: 17, margin: 0 }}>Newsroom appliance (V2)</h2>
        {appliance && !showRegister && (
          <span style={{ fontSize: 12, color: '#666' }}>Registered {new Date(appliance.registered_at).toLocaleDateString()}</span>
        )}
      </div>
      <p style={{ fontSize: 12, color: '#666', margin: '4px 0 12px' }}>
        Run a small local appliance to handle <strong>sensitive</strong> Grounded jobs (per your sensitivity rules) on
        your own hardware. Sensitive payloads never reach Anthropic when an appliance is registered + active.
      </p>

      {error && <div style={errorStyle}>{error}</div>}

      {secretReveal && (
        <div style={revealStyle}>
          <strong>Signing secret (shown once):</strong>
          <pre style={preStyle}>{secretReveal.secret}</pre>
          <p style={{ fontSize: 12, margin: '6px 0 0' }}>
            Copy this into the <code>APPLIANCE_SECRET</code> env var on your appliance. We do not store it in plaintext;
            after you dismiss this panel it cannot be retrieved — only re-generated by deleting + re-registering.
          </p>
          <button onClick={() => setSecretReveal(null)} style={{ ...btnSecondary, marginTop: 8 }}>I&apos;ve copied it</button>
        </div>
      )}

      {!appliance && !showRegister && (
        <button onClick={() => setShowRegister(true)} style={btnPrimary}>Register an appliance</button>
      )}

      {showRegister && (
        <RegisterForm
          onSaved={(id, secret) => {
            setShowRegister(false);
            setSecretReveal({ id, secret });
            load();
          }}
          onCancel={() => setShowRegister(false)}
        />
      )}

      {appliance && !showRegister && <ApplianceCard appliance={appliance} onChange={load} />}
    </section>
  );
}

function RegisterForm({ onSaved, onCancel }: { onSaved: (id: string, secret: string) => void; onCancel: () => void }) {
  const [displayName, setDisplayName] = useState('');
  const [dispatchUrl, setDispatchUrl] = useState('https://');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  async function submit(e: FormEvent) {
    e.preventDefault();
    setBusy(true); setErr(null);
    try {
      const res = await fetch('/api/appliances', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ display_name: displayName.trim(), dispatch_url: dispatchUrl.trim() }),
      });
      const j = await res.json();
      if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`);
      onSaved(j.id, j.signing_secret);
    } catch (e: any) {
      setErr(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <form onSubmit={submit} style={cardStyle}>
      <h3 style={subHeadStyle}>Register your appliance</h3>
      <label style={lbl}>Display name<input style={inp} value={displayName} onChange={(e) => setDisplayName(e.target.value)} required maxLength={100} placeholder="EnviroPress mini" /></label>
      <label style={lbl}>Dispatch URL
        <input style={inp} value={dispatchUrl} onChange={(e) => setDispatchUrl(e.target.value)} required placeholder="https://envpress-appliance.ts.net:8443" />
        <span style={{ fontSize: 11, color: '#888' }}>Fully-qualified URL the central app reaches your appliance at. Typically a Tailscale or Cloudflare Tunnel link.</span>
      </label>
      {err && <div style={errorStyle}>{err}</div>}
      <div style={{ display: 'flex', gap: 8, marginTop: 8 }}>
        <button type="submit" disabled={busy} style={btnPrimary}>{busy ? 'Registering…' : 'Register + show secret'}</button>
        <button type="button" onClick={onCancel} style={btnSecondary}>Cancel</button>
      </div>
    </form>
  );
}

function ApplianceCard({ appliance, onChange }: { appliance: Appliance; onChange: () => void }) {
  const [health, setHealth] = useState<Health | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [testResult, setTestResult] = useState<{ ok: boolean; duration_ms?: number; error?: string } | null>(null);

  async function loadHealth() {
    setError(null);
    try {
      const res = await fetch(`/api/appliances/${appliance.id}/health`);
      const j = await res.json();
      if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`);
      setHealth(j);
    } catch (e: any) {
      setError(e.message);
    }
  }
  useEffect(() => { loadHealth(); }, [appliance.id]);

  async function toggleStatus() {
    setBusy(true); setError(null);
    try {
      const next = appliance.status === 'active' ? 'paused' : 'active';
      const res = await fetch(`/api/appliances/${appliance.id}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: next }),
      });
      const j = await res.json();
      if (!res.ok) throw new Error(j.error || `HTTP ${res.status}`);
      onChange();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  async function testDispatch() {
    setBusy(true); setError(null); setTestResult(null);
    try {
      const res = await fetch(`/api/appliances/${appliance.id}/test-dispatch`, { method: 'POST' });
      const j = await res.json();
      setTestResult(j);
      if (!res.ok) setError(j.error || `HTTP ${res.status}`);
      loadHealth();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  async function destroy() {
    if (!confirm(`Delete appliance "${appliance.display_name}"? You'll need to re-register with a new signing secret.`)) return;
    setBusy(true); setError(null);
    try {
      const res = await fetch(`/api/appliances/${appliance.id}`, { method: 'DELETE' });
      if (!res.ok) {
        const j = await res.json();
        throw new Error(j.error || `HTTP ${res.status}`);
      }
      onChange();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <div style={cardStyle}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline' }}>
        <div>
          <h3 style={{ fontSize: 15, margin: '0 0 4px' }}>{appliance.display_name}</h3>
          <div style={{ fontSize: 12, color: '#666' }}>
            <code style={codeStyle}>{appliance.dispatch_url}</code>
          </div>
        </div>
        <StatusPill status={appliance.status} online={health?.online ?? false} />
      </div>

      <div style={{ display: 'flex', gap: 14, fontSize: 12, color: '#666', marginTop: 10 }}>
        <span>last seen: {appliance.last_seen_at ? new Date(appliance.last_seen_at).toLocaleString() : '—'}</span>
        {appliance.last_seen_version && <span>version: {appliance.last_seen_version}</span>}
        {appliance.registered_by_email && <span>by {appliance.registered_by_email}</span>}
      </div>

      {health && (
        <div style={{ fontSize: 12, color: '#444', margin: '10px 0' }}>
          Last 7 days: <strong>{health.last_7_days.completed}</strong> completed
          {' · '}
          <span style={{ color: health.last_7_days.failed > 0 ? '#a00' : '#888' }}>{health.last_7_days.failed} failed</span>
          {' · '}
          <span style={{ color: health.last_7_days.timeout > 0 ? '#a00' : '#888' }}>{health.last_7_days.timeout} timeout</span>
          {' · '}
          {health.last_7_days.in_flight} in-flight
        </div>
      )}

      <div style={{ display: 'flex', gap: 8, marginTop: 8, flexWrap: 'wrap' }}>
        <button onClick={testDispatch} disabled={busy} style={btnPrimary}>{busy ? 'Working…' : 'Test dispatch'}</button>
        <button onClick={toggleStatus} disabled={busy} style={btnSecondary}>
          {appliance.status === 'active' ? 'Pause' : 'Resume'}
        </button>
        <button onClick={destroy} disabled={busy} style={btnDanger}>Delete</button>
      </div>

      {testResult && (
        <div style={{ ...testResult.ok ? successStyle : errorStyle, marginTop: 10 }}>
          {testResult.ok
            ? `✓ Test dispatch succeeded in ${testResult.duration_ms ?? '—'}ms.`
            : `✗ Test dispatch failed: ${testResult.error}`}
        </div>
      )}

      {error && <div style={{ ...errorStyle, marginTop: 10 }}>{error}</div>}

      {health && health.recent_dispatches.length > 0 && (
        <details style={{ marginTop: 12 }}>
          <summary style={{ fontSize: 13, color: '#666', cursor: 'pointer' }}>Recent dispatches ({health.recent_dispatches.length})</summary>
          <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12, marginTop: 6 }}>
            <thead>
              <tr>
                <Th>When</Th><Th>Endpoint</Th><Th>Status</Th><Th>HTTP</Th><Th>Duration</Th><Th>Error</Th>
              </tr>
            </thead>
            <tbody>
              {health.recent_dispatches.map((d) => (
                <tr key={d.id}>
                  <Td>{new Date(d.dispatched_at).toLocaleString()}</Td>
                  <Td><code style={codeStyle}>{d.endpoint}</code></Td>
                  <Td>{d.status}</Td>
                  <Td>{d.http_status ?? '—'}</Td>
                  <Td>{d.duration_ms != null ? `${d.duration_ms}ms` : '—'}</Td>
                  <Td style={{ color: d.error ? '#a00' : '#888' }}>{d.error || '—'}</Td>
                </tr>
              ))}
            </tbody>
          </table>
        </details>
      )}
    </div>
  );
}

function StatusPill({ status, online }: { status: string; online: boolean }) {
  const map: Record<string, { bg: string; fg: string; label: string }> = {
    active: online
      ? { bg: '#e6f4ea', fg: '#0a7d2a', label: 'active · online' }
      : { bg: '#fff4e1', fg: '#915d00', label: 'active · offline' },
    paused: { bg: '#f0f0f0', fg: '#666', label: 'paused' },
    failed: { bg: '#fde8e8', fg: '#a00', label: 'failed' },
  };
  const c = map[status] || { bg: '#f0f0f0', fg: '#666', label: status };
  return <span style={{ display: 'inline-block', padding: '2px 10px', borderRadius: 4, fontSize: 11, background: c.bg, color: c.fg, fontWeight: 600 }}>{c.label}</span>;
}

function Th({ children }: { children: React.ReactNode }) {
  return <th style={{ textAlign: 'left', padding: '4px 6px', borderBottom: '1px solid #ddd', fontSize: 11, color: '#666' }}>{children}</th>;
}
function Td({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return <td style={{ padding: '4px 6px', borderBottom: '1px solid #f0f0f0', fontSize: 12, ...style }}>{children}</td>;
}

const cardStyle: React.CSSProperties = {
  background: '#fafbfd', border: '1px solid #e1e4e8', borderRadius: 8, padding: 14, marginTop: 10,
};
const subHeadStyle: React.CSSProperties = { fontSize: 13, textTransform: 'uppercase', letterSpacing: 0.5, color: '#666', margin: '0 0 8px' };
const lbl: React.CSSProperties = { display: 'block', fontSize: 13, color: '#444', margin: '8px 0', fontWeight: 500 };
const inp: React.CSSProperties = {
  display: 'block', width: '100%', padding: '7px 10px', fontSize: 13,
  border: '1px solid #ccc', borderRadius: 4, marginTop: 4, boxSizing: 'border-box', fontFamily: 'inherit',
};
const codeStyle: React.CSSProperties = { fontSize: 11, background: '#eef0f3', padding: '1px 5px', borderRadius: 3, color: '#444' };
const btnPrimary: React.CSSProperties = { padding: '7px 14px', background: '#0066cc', color: 'white', border: 'none', borderRadius: 4, fontSize: 13, cursor: 'pointer', fontWeight: 600 };
const btnSecondary: React.CSSProperties = { padding: '7px 14px', background: 'white', color: '#444', border: '1px solid #ccc', borderRadius: 4, fontSize: 13, cursor: 'pointer' };
const btnDanger: React.CSSProperties = { padding: '7px 14px', background: 'white', color: '#a00', border: '1px solid #f5b1b1', borderRadius: 4, fontSize: 13, cursor: 'pointer' };
const errorStyle: React.CSSProperties = { background: '#fff3f3', border: '1px solid #f5b1b1', color: '#900', padding: 10, borderRadius: 6, fontSize: 13 };
const successStyle: React.CSSProperties = { background: '#e6f4ea', border: '1px solid #b6e0bd', color: '#0a7d2a', padding: 10, borderRadius: 6, fontSize: 13 };
const revealStyle: React.CSSProperties = { background: '#fff8e1', border: '2px solid #f5cf6b', borderRadius: 8, padding: 14, marginTop: 10 };
const preStyle: React.CSSProperties = { background: 'white', border: '1px solid #ddd', borderRadius: 4, padding: 8, fontSize: 13, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', overflowX: 'auto', margin: '6px 0' };
