// Local Ollama fallback. Only invoked by lib/claude.js when an Anthropic call
// fails because of credit exhaustion, persistent rate-limiting, or overload.
//
// The goal is availability, not cost-shopping. The Haiku-only rule still
// stands for normal operation — Ollama exists so a newsroom in the middle of
// filing a brief doesn't get bricked when the cohort's Anthropic credit hits
// zero. Brief responses generated by the fallback are flagged so the UI can
// show a degraded-mode badge ("⚠ generated by local fallback model").
//
// Install once:
//   brew install ollama
//   ollama pull gemma3:12b      (default — strong general-purpose, ~8 GB)
//   ollama serve                (usually runs as a launchd service automatically)
//
// Any chat-tuned model exposed by Ollama works. Override with
// ANCHOR_OLLAMA_FALLBACK_MODEL=llama3.1:8b (or whatever you have pulled).
//
// Env:
//   ANCHOR_OLLAMA_FALLBACK_URL    default http://localhost:11434
//   ANCHOR_OLLAMA_FALLBACK_MODEL  default gemma3:12b

const { pool } = require('./db');

const DEFAULT_URL = process.env.ANCHOR_OLLAMA_FALLBACK_URL || 'http://localhost:11434';
const DEFAULT_MODEL = process.env.ANCHOR_OLLAMA_FALLBACK_MODEL || 'gemma3:12b';

// Anchor messages can carry content as a string OR an array of content blocks
// (Anthropic's shape). Ollama only accepts flat strings, so we flatten — text
// blocks are joined, non-text blocks (images, tool calls) are dropped with a
// placeholder so the model knows something was elided.
function flattenContent(content) {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return String(content ?? '');
  return content
    .map((b) => {
      if (!b || typeof b !== 'object') return String(b ?? '');
      if (b.type === 'text') return b.text || '';
      if (b.type === 'image') return '[image elided in fallback]';
      if (b.type === 'tool_use' || b.type === 'tool_result') {
        return '[tool block elided in fallback]';
      }
      return '';
    })
    .filter(Boolean)
    .join('\n');
}

function buildOllamaMessages(system, messages) {
  const out = [];
  if (system) out.push({ role: 'system', content: String(system) });
  for (const m of messages) {
    out.push({ role: m.role, content: flattenContent(m.content) });
  }
  return out;
}

async function logOllamaCost({ model, inputTokens, outputTokens, context }) {
  await pool.query(
    `INSERT INTO api_costs
       (service, model, endpoint, agent, newsroom_id, user_id,
        input_tokens, output_tokens, cost_usd)
     VALUES ('ollama', $1, $2, $3, $4, $5, $6, $7, 0)`,
    [
      model,
      context.endpoint || null,
      context.agent || null,
      context.newsroomId || null,
      context.userId || null,
      inputTokens || 0,
      outputTokens || 0,
    ]
  );
  return { costUsd: 0, model, inputTokens: inputTokens || 0, outputTokens: outputTokens || 0 };
}

/**
 * Send a message to a local Ollama server. Same return shape as lib/claude.js
 * chat() so callers don't need to branch.
 *
 * @param {object} opts
 * @param {string} opts.system
 * @param {Array}  opts.messages
 * @param {number} [opts.maxTokens]   Default 4096.
 * @param {object} [opts.context]     { newsroomId, userId, agent, endpoint }
 * @returns {Promise<{
 *   text: string,
 *   raw: object,
 *   cost: { costUsd: number, model: string, inputTokens: number, outputTokens: number },
 *   usedFallback: true,
 *   fallbackModel: string,
 * }>}
 */
async function chatOllama({ system, messages, maxTokens = 4096, context = {} }) {
  const url = `${DEFAULT_URL.replace(/\/$/, '')}/api/chat`;
  const body = {
    model: DEFAULT_MODEL,
    messages: buildOllamaMessages(system, messages),
    stream: false,
    options: { num_predict: maxTokens },
  };

  let response;
  try {
    response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
  } catch (err) {
    const e = new Error(
      `Ollama unreachable at ${url}: ${err.message}. Is 'ollama serve' running?`
    );
    e.cause = err;
    throw e;
  }

  if (!response.ok) {
    const detail = await response.text().catch(() => '');
    throw new Error(`Ollama returned ${response.status}: ${detail.slice(0, 500)}`);
  }

  const json = await response.json();
  // Ollama /api/chat response shape:
  //   { model, message: { role, content }, done, prompt_eval_count, eval_count, ... }
  const text = json?.message?.content || '';
  const inputTokens = json?.prompt_eval_count || 0;
  const outputTokens = json?.eval_count || 0;

  const cost = await logOllamaCost({
    model: json?.model || DEFAULT_MODEL,
    inputTokens,
    outputTokens,
    context,
  });

  return {
    text,
    raw: json,
    cost,
    usedFallback: true,
    fallbackModel: json?.model || DEFAULT_MODEL,
  };
}

// Heuristics for "Anthropic isn't going to serve this brief — switch to local."
function shouldFallbackTo(err) {
  if (!err) return false;
  const status = err.status || err.statusCode;
  const msg = (err.message || '').toLowerCase();

  // Credit balance exhausted — Anthropic returns 400 with this phrasing.
  if (status === 400 && (msg.includes('credit balance') || msg.includes('insufficient_quota'))) {
    return true;
  }
  // Rate-limited or overloaded after the retry loop gave up.
  if (status === 429 || status === 529) return true;
  // Connectivity issues to Anthropic after retries.
  if (err.code === 'ECONNRESET' || err.code === 'ETIMEDOUT') return true;
  if (err.name === 'APIConnectionError' || err.name === 'APIConnectionTimeoutError') return true;
  return false;
}

module.exports = { chatOllama, shouldFallbackTo };
